<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function getConnection():?string{return config('tenancy.tenant_connection','tenant');}
 public function up():void{
  if(!Schema::hasTable('sales_fulfillment_requests'))Schema::create('sales_fulfillment_requests',function(Blueprint$t){$t->id();$t->unsignedBigInteger('organization_id');$t->uuid('organization_mapping_uuid');$t->uuid('request_uuid');$t->unsignedBigInteger('source_invoice_id');$t->string('source_invoice_number')->nullable();$t->char('source_revision',64);$t->string('source_status');$t->unsignedBigInteger('posted_invoice_journal_id')->nullable();$t->unsignedBigInteger('customer_id');$t->date('invoice_date');$t->date('requested_ship_date')->nullable();$t->string('currency_code',3);$t->string('base_currency_code',3);$t->decimal('exchange_rate',20,10)->nullable();$t->date('exchange_rate_date')->nullable();$t->string('status')->default('pending');$t->unsignedBigInteger('warehouse_id')->nullable();$t->unsignedBigInteger('sales_order_id')->nullable();$t->json('source_payload');$t->timestamp('approved_at')->nullable();$t->unsignedBigInteger('approved_by')->nullable();$t->char('approved_revision',64)->nullable();$t->timestamps();$t->unique(['organization_id','request_uuid'],'sfr_org_uuid_unique');$t->unique(['organization_id','source_invoice_id'],'sfr_org_invoice_unique');});
  if(!Schema::hasTable('sales_fulfillment_request_lines'))Schema::create('sales_fulfillment_request_lines',function(Blueprint$t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('fulfillment_request_id');$t->string('source_line_id');$t->unsignedBigInteger('item_id');$t->unsignedBigInteger('entered_unit_id');$t->decimal('requested_qty',18,4);$t->decimal('fulfilled_qty',18,4)->default(0);$t->decimal('unit_price',18,4);$t->decimal('discount_rate',18,4)->default(0);$t->unsignedBigInteger('sales_order_line_id')->nullable();$t->timestamps();$t->unique(['fulfillment_request_id','source_line_id'],'sfrl_source_unique');});
  if(!Schema::hasTable('sales_document_outbox'))Schema::create('sales_document_outbox',function(Blueprint$t){$t->id();$t->unsignedBigInteger('organization_id');$t->uuid('organization_mapping_uuid');$t->uuid('event_uuid');$t->string('source_key')->unique('sdo_source_unique');$t->string('event_type');$t->json('payload');$t->char('payload_hash',64);$t->string('status')->default('pending');$t->unsignedInteger('attempts')->default(0);$t->timestamp('next_attempt_at')->nullable();$t->uuid('lease_token')->nullable();$t->timestamp('lease_expires_at')->nullable();$t->json('response')->nullable();$t->string('last_error')->nullable();$t->timestamps();$t->index(['organization_id','status','next_attempt_at'],'sdo_delivery_index');});
 }
 public function down():void{} // Immutable source/audit/line facts survive code rollback.
};
