<?php
namespace Tests\Unit\Integration;
use App\Services\Integration\DocumentIncidentFacts;
use PHPUnit\Framework\TestCase;
final class DocumentIncidentFactsTest extends TestCase {
 private function rows():array {return [(object)['id'=>71,'event_uuid'=>'immutable-event','status'=>'retry','attempts'=>1,'receiver_response'=>json_encode(['reason'=>'party_identity_review_required','entity_type'=>'supplier','source_id'=>9]),'payload'=>json_encode(['receipt'=>['supplier_name'=>'Original supplier']])],(object)['id'=>31,'warehouse_id'=>4,'grn_number'=>'GRN-QA-31','deleted_at'=>null,'reversed_at'=>null,'reversal_id'=>null]];}
 public function test_retries_and_timestamps_do_not_duplicate_incident_identity():void {[$row,$native]=$this->rows();$one=DocumentIncidentFacts::fromRows('receipt',$row,$native,'mapping-one');$row->attempts=20;$row->updated_at='later';$two=DocumentIncidentFacts::fromRows('receipt',$row,$native,'mapping-one');$this->assertSame(DocumentIncidentFacts::fingerprint($one),DocumentIncidentFacts::fingerprint($two));}
 public function test_actual_terminal_failure_and_resolution_are_distinct():void {[$row,$native]=$this->rows();$row->status='intervention';$one=DocumentIncidentFacts::fromRows('receipt',$row,$native,'mapping-one');$row->status='sent';$row->receiver_response=json_encode(['bill_id'=>45]);$two=DocumentIncidentFacts::fromRows('receipt',$row,$native,'mapping-one');$this->assertSame('intervention',$one['state']);$this->assertSame('resolved',$two['state']);$this->assertSame(45,$two['destination_document_id']);$this->assertNull($two['reason']);$this->assertNotSame(DocumentIncidentFacts::fingerprint($one),DocumentIncidentFacts::fingerprint($two));}
 public function test_untrusted_remote_error_text_and_secret_are_not_exposed():void {[$row,$native]=$this->rows();$row->receiver_response=json_encode(['reason'=>'secret-token-do-not-expose','message'=>'raw request secret','missing_information'=>['supplier_mapping_required','raw-secret']]);$facts=DocumentIncidentFacts::fromRows('receipt',$row,$native,'mapping-one');$this->assertSame('delivery_pending',$facts['reason']);$this->assertSame(['supplier_mapping_required'],$facts['missing_information']);$this->assertStringNotContainsString('secret',json_encode($facts));}
 public function test_native_reversal_does_not_falsely_cancel_financial_document():void {[$row,$native]=$this->rows();$native->reversal_id=123;$facts=DocumentIncidentFacts::fromRows('receipt',$row,$native,'mapping-one');$this->assertSame('cancelled',$facts['state']);$this->assertArrayNotHasKey('bill_status',$facts);$this->assertArrayNotHasKey('payment_status',$facts);}
 public function test_mapping_and_document_identity_are_part_of_deduplication():void {[$row,$native]=$this->rows();$one=DocumentIncidentFacts::fromRows('receipt',$row,$native,'mapping-one');$two=DocumentIncidentFacts::fromRows('receipt',$row,$native,'mapping-two');$this->assertNotSame(DocumentIncidentFacts::fingerprint($one),DocumentIncidentFacts::fingerprint($two));}
}
