import React, {useEffect,useRef,useState} from 'react';
import {getLocale} from '../i18n/index.js';
import {localizePurchasingNotification} from './purchasingNotificationLocale.mjs';
export default function PurchasingNotificationBell({organizationId}) {
 const [open,setOpen]=useState(false),[items,setItems]=useState([]),[unread,setUnread]=useState(0),[error,setError]=useState(false),[busy,setBusy]=useState(false); const box=useRef(null),scope=useRef(organizationId);scope.current=organizationId;const [dataOrg,setDataOrg]=useState(null);const ar=getLocale()==='ar';const base=(window.SOLASTOCK_BASE_PATH||'/inventory')+'/api/v1/purchasing/notifications';
 const labels={title:ar?'إشعارات الاستلام':'Receiving notifications',empty:ar?'لا توجد إشعارات':'No notifications',error:ar?'تعذر تحميل الإشعارات. حاول مجدداً.':'Notifications could not be loaded. Try again.',retry:ar?'إعادة المحاولة':'Retry'};
 async function load(){const requestedOrg=organizationId;if(!requestedOrg)return;setBusy(true);try{const res=await fetch(base,{credentials:'same-origin',headers:{Accept:'application/json'}});const data=await res.json();if(!res.ok||data.success!==true)throw Error();if(scope.current!==requestedOrg)return;setDataOrg(requestedOrg);setItems(data.data.items||[]);setUnread(data.data.unread||0);setError(false);}catch{if(scope.current===requestedOrg)setError(true);}finally{if(scope.current===requestedOrg)setBusy(false)}}
 useEffect(()=>{setOpen(false);setItems([]);setUnread(0);if(!organizationId)return;void load();const timer=setInterval(()=>{if(!document.hidden)void load()},60000);return()=>clearInterval(timer)},[organizationId]);
 useEffect(()=>{if(!open)return;function close(e){if(e.key==='Escape'){setOpen(false);box.current?.querySelector('button')?.focus()}else if(e.type==='pointerdown'&&!box.current?.contains(e.target))setOpen(false)}document.addEventListener('keydown',close);document.addEventListener('pointerdown',close);return()=>{document.removeEventListener('keydown',close);document.removeEventListener('pointerdown',close)}},[open]);
 async function visit(item){if(busy)return;setBusy(true);try{const res=await fetch(base+'/'+encodeURIComponent(item.id)+'/read',{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]')?.content||''},body:'{}'});if(!res.ok)throw Error();const next=new URL(item.action_url,location.origin);if(next.origin!==location.origin||!next.pathname.startsWith((window.SOLASTOCK_BASE_PATH||'/inventory')+'/receiving-requests'))throw Error();location.assign(next.href);}catch{setError(true);setBusy(false)}}
 return <div ref={box} style={{position:'relative'}}><button type="button" className="icon-btn" aria-label={labels.title} aria-expanded={open} aria-controls="stock-receiving-notifications" onClick={()=>{setOpen(!open);if(!open)void load()}}><i className="fa-solid fa-bell" aria-hidden="true"/>{dataOrg===organizationId&&unread>0&&<span style={{fontSize:10,fontWeight:700}}>{unread>99?'99+':unread}</span>}</button>{open&&<section id="stock-receiving-notifications" aria-label={labels.title} style={{position:'absolute',insetInlineEnd:0,top:'calc(100% + 8px)',zIndex:70,width:'min(340px, calc(100vw - 28px))',maxHeight:'70vh',overflowY:'auto',background:'var(--surface-1,#fff)',color:'var(--ink,#222)',border:'1px solid var(--line-soft,#ddd)',borderRadius:12,boxShadow:'0 10px 30px #0002',padding:12}}><strong>{labels.title}</strong>{error?<div role="alert"><p>{labels.error}</p><button type="button" disabled={busy} onClick={load}>{labels.retry}</button></div>:dataOrg!==organizationId||items.length===0?<p>{labels.empty}</p>:items.map(item=>{const localized=localizePurchasingNotification(item,ar?'ar':'en');return <button key={item.id} type="button" disabled={busy} onClick={()=>visit(item)} style={{display:'block',width:'100%',textAlign:'start',padding:'10px 4px',background:'transparent',border:'none',borderBlockEnd:'1px solid var(--line-soft,#ddd)',color:'inherit',cursor:'pointer'}}><strong style={{display:'block'}}>{localized.title}</strong><span style={{display:'block',fontSize:12,whiteSpace:'pre-line'}}>{localized.body}</span></button>})}</section>}</div>
}
