<?php

namespace App\Services\InventoryWorkspace;

/** Closed contract: no arbitrary route/controller names, administration, transport, or provisioning. */
final class WorkspaceActions
{
    public const ALLOWED = [
        'purchasing.bill.context', 'purchasing.bill.receipt', 'purchasing.bill.reserve', 'purchasing.bill.cost-adjustment.prepare',
        'purchasing.request.upsert', 'purchasing.request.status', 'purchasing.request.cancel',
        'finance-sources.suppliers', 'finance-sources.customers',
        'finance-sources.receipts', 'finance-sources.receipt',
        'finance-sources.shipments', 'finance-sources.shipment',
        'finance-sources.returns', 'finance-sources.return',
        'finance-allocations.reserve', 'finance-allocations.commit',
        'finance-allocations.release', 'finance-allocations.reverse',
        'finance-allocations.cost-adjustment.prepare', 'finance-allocations.cost-adjustment.apply',
        'finance-allocations.cost-adjustment.reverse',
        'migration-references.link', 'historical-fifo.review', 'historical-fifo.apply',
        // Native operational documents retain their own permissions, dates,
        // stock guards and outbox lifecycle under the signed command receipt.
        'suppliers.index', 'suppliers.show', 'suppliers.store',
        'customers.index', 'customers.show', 'customers.store',
        'po.index', 'po.show', 'po.store',
        'sales-orders.index', 'sales-orders.show', 'sales-orders.store',
        'grn.index', 'grn.show', 'grn.store', 'grn.post',
        'shipments.index', 'shipments.show', 'shipments.store', 'shipments.post',
        'sales-returns.index', 'sales-returns.show', 'sales-returns.store', 'sales-returns.post',
        'reorder-rules.index',
        'reorder-rules.show',
        'reorder-rules.update',
        'workspace.dashboard',
        'workspace.lookups',
        'workspace.reorder',
        'settings.reorder.calculate',
        'settings.reorder.store',
        'items.index',
        'items.show',
        'items.store',
        'catalog-references.ensure',
        'finance-allocations.review-status',
        'items.migration-requirements', 'items.migration-create', 'items.migration-link',
        'items.update',
        'items.movements',
        'items.movements.export',
        'items.valuation',
        'warehouses.index',
        'warehouses.show',
        'warehouses.store',
        'warehouses.update',
        'zones.store',
        'zones.update',
        'bins.store',
        'bins.update',
        'balances.index',
        'ledger.index',
        'opening.index',
        'opening.migrate', 'opening.requirements',
        'opening.show',
        'opening.store',
        'opening.update',
        'opening.post',
        'opening.reverse',
        'audit-logs.index',
        'transfers.index',
        'transfers.show',
        'transfers.store',
        'transfers.update',
        'transfers.post',
        'transfers.ship',
        'transfers.receive',
        'counts.index',
        'counts.show',
        'counts.prefill',
        'counts.store',
        'counts.update',
        'counts.post',
        'adjustments.index',
        'adjustments.show',
        'adjustments.store',
        'adjustments.update',
        'adjustments.post',
        'adjustments.reverse',
        'lots.index',
        'lots.show',
        'lots.movements',
        'serials.index',
        'serials.show',
        'serials.lifecycle',
    ];
}
