<?php

namespace App\Services\InventoryWorkspace;

/** Closed contract: no arbitrary route/controller names, administration, transport, or provisioning. */
final class WorkspaceActions
{
    public const ALLOWED = [
        'finance-sources.suppliers', 'finance-sources.customers',
        'finance-sources.receipts', 'finance-sources.receipt',
        'finance-sources.shipments', 'finance-sources.shipment',
        'finance-sources.returns', 'finance-sources.return',
        'finance-allocations.reserve', 'finance-allocations.commit',
        'finance-allocations.release', 'finance-allocations.reverse',
        'finance-allocations.cost-adjustment.prepare', 'finance-allocations.cost-adjustment.apply',
        'finance-allocations.cost-adjustment.reverse',
        'reorder-rules.index',
        'reorder-rules.show',
        'reorder-rules.update',
        'workspace.dashboard',
        'workspace.lookups',
        'workspace.reorder',
        'settings.reorder.calculate',
        'settings.reorder.store',
        'items.index',
        'items.show',
        'items.store',
        'items.update',
        'items.movements',
        'items.valuation',
        'warehouses.index',
        'warehouses.show',
        'warehouses.store',
        'warehouses.update',
        'zones.store',
        'zones.update',
        'bins.store',
        'bins.update',
        'balances.index',
        'ledger.index',
        'opening.index',
        'opening.show',
        'opening.store',
        'opening.update',
        'opening.post',
        'opening.reverse',
        'audit-logs.index',
        'transfers.index',
        'transfers.show',
        'transfers.store',
        'transfers.update',
        'transfers.post',
        'transfers.ship',
        'transfers.receive',
        'counts.index',
        'counts.show',
        'counts.prefill',
        'counts.store',
        'counts.update',
        'counts.post',
        'adjustments.index',
        'adjustments.show',
        'adjustments.store',
        'adjustments.update',
        'adjustments.post',
        'adjustments.reverse',
        'lots.index',
        'lots.show',
        'lots.movements',
        'serials.index',
        'serials.show',
        'serials.lifecycle',
    ];
}
