import React, {useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../services/api';
import {useApiQuery} from '../hooks/useApiQuery';
import {useTenant} from '../stores/tenant';
import {useI18n} from '../i18n/context';

export default function CashFulfillmentRequestsPage() {
 const tenant=useTenant();const {locale}=useI18n();const ar=locale==='ar';const [filter,setFilter]=useState('active');const [selected,setSelected]=useState(null);
 const query=useApiQuery(['cash-fulfillment',tenant.organization_id,filter],()=>api.cashFulfillmentRequests(filter),{fallback:[]});
 const states={pending:ar?'بانتظار التسليم':'Awaiting dispatch',partial:ar?'تسليم جزئي':'Partially dispatched',complete:ar?'مكتمل':'Completed',cancelled:ar?'ملغى':'Cancelled'};
 return <section className="page"><header className="page-head"><h1>{ar?'تسليم المبيعات النقدية':'Cash sale dispatch'}</h1></header><p>{ar?'تم تسجيل البيع والدفع في SolaCount. أكّد التسليم الفعلي هنا فقط عند خروج البضاعة.':'The sale and payment are recorded in SolaCount. Confirm actual dispatch only when the goods leave the warehouse.'}</p>
 <nav aria-label={ar?'حالة التسليم':'Dispatch status'} style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}>{['active','history','cancelled'].map(v=><button className={filter===v?'btn btn--primary':'btn'} key={v} aria-pressed={filter===v} onClick={()=>{setFilter(v);setSelected(null);}}>{({active:ar?'النشطة':'Active',history:ar?'السجل':'History',cancelled:ar?'الملغاة':'Cancelled'})[v]}</button>)}</nav>
 {query.isError?<div role="alert" className="banner banner--warn">{ar?'تعذر تحميل الطلبات.':'Requests could not be loaded.'}<button className="btn" onClick={()=>query.refetch()}>{ar?'إعادة المحاولة':'Retry'}</button></div>:query.isLoading?<p>{ar?'جار التحميل…':'Loading…'}</p>:!query.data?.length?<div className="empty-state">{ar?'لا توجد طلبات بيع نقدي في هذه القائمة.':'No cash sale requests in this list.'}</div>:query.data.map(r=><article className="panel" key={r.request_uuid} style={{marginBottom:16,overflowWrap:'anywhere'}}><h2>{r.source_document_number}</h2><p>{states[r.status]??(ar?'قيد المراجعة':'Needs review')}</p><div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>{ar?'الصنف':'Item'}</th><th>{ar?'المطلوب':'Expected'}</th><th>{ar?'تم تسليمه':'Dispatched'}</th><th>{ar?'الملغى':'Cancelled'}</th></tr></thead><tbody>{r.lines.map(l=><tr key={l.id}><td>{l.item_name??l.item_id}</td><td>{l.requested_quantity}</td><td>{l.fulfilled_quantity}</td><td>{l.cancelled_quantity??'0.0000'}</td></tr>)}</tbody></table></div>{r.physical_documents?.map(d=><p key={d.id}><Link to={`/shipments/${d.id}`}>{d.number}</Link></p>)}{['pending','partial'].includes(r.status)&&<button className="btn btn--primary" onClick={()=>setSelected(selected===r.id?null:r.id)}>{ar?'مراجعة التسليم':'Review dispatch'}</button>}{selected===r.id&&<CashDispatchForm key={`${tenant.organization_id}:${r.id}`} id={r.id} org={tenant.organization_id} ar={ar} onDone={()=>query.refetch()}/>}</article>)}
 </section>;
}
function CashDispatchForm({id,org,ar,onDone}) {
 const query=useApiQuery(['cash-dispatch-options',org,id],()=>api.cashFulfillmentOptions(id));const data=query.data;
 const [warehouse,setWarehouse]=useState('');const [date,setDate]=useState('');const [lines,setLines]=useState({});const [reserve,setReserve]=useState(false);const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const storageKey=`stock-cash-dispatch:${org}:${id}`;
 const [saved,setSaved]=useState(()=>{try{return JSON.parse(sessionStorage.getItem(storageKey)||'null');}catch{return null;}});
 function remember(body){sessionStorage.setItem(storageKey,JSON.stringify(body));setSaved(body);}
 function finish(){sessionStorage.removeItem(storageKey);setSaved(null);setLines({});setConfirmed(false);setNotice(ar?'تم تأكيد التسليم.':'Dispatch confirmed.');query.refetch();onDone();}
 async function approve(){setBusy(true);setError('');try{await api.approveCashFulfillment(id,{warehouse_id:Number(warehouse||data?.default_warehouse_id)});query.refetch();onDone();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function check(){setBusy(true);setError('');try{const result=await api.cashFulfillmentStatus(id,saved.operation_uuid);if(result.data.status==='completed')finish();else setNotice(ar?'العملية محفوظة. أعد محاولة التسليم نفسه.':'The operation is saved. Retry this same dispatch.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function submit(e){e.preventDefault();if(!confirmed||busy)return;setBusy(true);setError('');try{
  let body=saved;
  if(!body){body={operation_uuid:crypto.randomUUID(),warehouse_id:Number(data.request.warehouse_id),physical_date:date,confirm_dispatch:true,reserve_stock:reserve,lines:data.lines.filter(l=>Number(lines[l.request_line_id]?.quantity||0)>0).map(l=>({request_line_id:l.request_line_id,source_document_line_id:l.source_document_line_id,unit_id:l.unit_id,...lines[l.request_line_id]}))};if(!body.lines.length)throw Error(ar?'أدخل كمية تم تسليمها فعلياً.':'Enter an actual dispatched quantity.');remember(body);}
  await api.dispatchCashFulfillment(id,body);finish();
 }catch(e){setError(e.message);if(!e.outcomeUnknown && e.status===422){sessionStorage.removeItem(storageKey);setSaved(null);}}finally{setBusy(false);}}
 function value(l,k,v){setLines(current=>({...current,[l.request_line_id]:{...current[l.request_line_id],[k]:v}}));}
 if(query.isError)return <p role="alert">{ar?'تعذر مراجعة الطلب أو لا تملك صلاحية المستودع.':'The request cannot be reviewed or you do not have warehouse access.'}</p>;
 if(!data)return <p>{ar?'جار التحميل…':'Loading…'}</p>;
 const wh=data.warehouses.find(w=>w.id===data.request.warehouse_id);
 return <div style={{marginTop:16}}>{error&&<div role="alert" className="banner banner--warn">{error}</div>}{notice&&<p role="status">{notice}</p>}
 {data.can_approve&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><label>{ar?'المستودع':'Warehouse'}<select value={warehouse||data.default_warehouse_id||''} onChange={e=>setWarehouse(e.target.value)} disabled={busy}><option value="">{ar?'اختر مستودعاً':'Choose a warehouse'}</option>{data.warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><button className="btn btn--primary" onClick={approve} disabled={busy||!(warehouse||data.default_warehouse_id)}>{ar?'اعتماد المستودع':'Approve warehouse'}</button></div>}
 {saved&&<div className="banner"><p>{ar?'توجد عملية تسليم محفوظة. تحقق من النتيجة قبل المحاولة مجدداً؛ لا تنشئ عملية أخرى.':'A dispatch operation is saved. Check its outcome before retrying; do not create another operation.'}</p><button className="btn" disabled={busy} onClick={check}>{ar?'التحقق من النتيجة':'Check outcome'}</button></div>}
 {(data.can_execute||saved)&&<form onSubmit={submit}><p>{ar?'المستودع':'Warehouse'}: {wh?.name}</p><label>{ar?'تاريخ التسليم':'Dispatch date'}<input type="date" required value={saved?.physical_date||date} disabled={busy||!!saved} onChange={e=>setDate(e.target.value)}/></label>
 {data.lines.map(l=><fieldset key={l.request_line_id} disabled={busy||!!saved} style={{margin:'12px 0',minWidth:0}}><legend>{l.item_name} · {ar?'المتبقي':'Remaining'} {l.remaining_quantity} {l.unit_name}</legend><label>{ar?'الكمية التي تم تسليمها':'Actual dispatched quantity'}<input type="number" min="0" max={l.remaining_quantity} step="0.0001" value={lines[l.request_line_id]?.quantity||''} onChange={e=>value(l,'quantity',e.target.value)}/></label>
 {wh?.bins?.length>0&&<label>{ar?'الموقع':'Bin'}<select onChange={e=>value(l,'bin_id',e.target.value?Number(e.target.value):null)}><option value="">—</option>{wh.bins.map(b=><option key={b.id} value={b.id}>{b.name||b.code}</option>)}</select></label>}
 {l.requires_variant&&<label>{ar?'المتغير':'Variant'}<select required={Number(lines[l.request_line_id]?.quantity||0)>0} onChange={e=>value(l,'variant_id',Number(e.target.value))}><option value="">—</option>{l.variant_choices.map(v=><option key={v.id} value={v.id}>{v.sku}</option>)}</select></label>}
 {l.requires_lot&&<label>{ar?'التشغيلة':'Lot'}<select required={Number(lines[l.request_line_id]?.quantity||0)>0} onChange={e=>value(l,'lot_id',Number(e.target.value))}><option value="">—</option>{l.lot_choices.filter(v=>v.warehouse_id===data.request.warehouse_id).map(v=><option key={`${v.id}:${v.bin_id}`} value={v.id}>{v.lot_code} · {v.available_quantity} · {v.expiry_date||''}</option>)}</select></label>}
 {l.requires_serials&&<label>{ar?'الأرقام التسلسلية':'Serial numbers'}<select multiple required={Number(lines[l.request_line_id]?.quantity||0)>0} onChange={e=>value(l,'serial_ids',[...e.target.selectedOptions].map(v=>Number(v.value)))}>{l.serial_choices.filter(v=>v.warehouse_id===data.request.warehouse_id).map(v=><option key={v.id} value={v.id}>{v.serial}</option>)}</select></label>}
 </fieldset>)}{data.can_reserve&&<label><input type="checkbox" checked={reserve} onChange={e=>setReserve(e.target.checked)} disabled={busy||!!saved}/>{ar?'حجز الكميات المحددة للتسليم وفق السياسة الحالية.':'Reserve the selected quantities for dispatch under the existing policy.'}</label>}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy}/>{ar?'أؤكد خروج الكميات المحددة فعلياً من المستودع.':'I confirm the selected quantities physically left the warehouse.'}</label><div style={{marginTop:12}}><button type="submit" className="btn btn--primary" disabled={busy||!confirmed}>{busy?(ar?'جار التأكيد…':'Confirming…'):saved?(ar?'إعادة محاولة التسليم المحفوظ':'Retry saved dispatch'):(ar?'تأكيد التسليم':'Confirm dispatch')}</button></div></form>}
 {!data.can_execute&&!data.can_approve&&!saved&&<p>{ar?'التسليم غير متاح حالياً. تحقق من الاعتماد والصلاحيات وحالة الطلب.':'Dispatch is currently unavailable. Check approval, permissions, and request state.'}</p>}
 </div>;
}
