import React, {useState} from 'react';
import {Link, useSearchParams} from 'react-router-dom';
import {WarehousePicker} from '../components/pickers';
import {api} from '../services/api';
import {useApiQuery} from '../hooks/useApiQuery';
import {useCan} from '../stores/meta';
import {useTenant} from '../stores/tenant';
import {useI18n} from '../i18n/context';
export default function FulfillmentRequestsPage() {
 const tenant=useTenant();const {locale}=useI18n();const ar=locale==='ar';const canApprove=useCan('inventory.manage_sales_orders');const [params,setParams]=useSearchParams();const filter=['active','cancelled','history'].includes(params.get('status'))?params.get('status'):'active';const selected=/^\d+$/.test(params.get('request')??'')?Number(params.get('request')):null;
 const [warehouses,setWarehouses]=useState({});const [error,setError]=useState('');const query=useApiQuery(['fulfillment-requests',tenant.organization_id,filter,selected],()=>selected?api.fulfillmentRequest(selected):api.fulfillmentRequests(filter),{fallback:[]});const rows=selected&&query.data?[query.data]:Array.isArray(query.data)?query.data:[];
 const statuses={pending:ar?'بانتظار التسليم':'Pending dispatch',partial:ar?'تسليم جزئي':'Partially dispatched',complete:ar?'مكتمل':'Fully dispatched',cancelled:ar?'ملغى':'Cancelled'};
 async function approve(request){try{await api.approveFulfillmentRequest(request.id,{warehouse_id:warehouses[request.id]});setError('');query.refetch();}catch(e){setError(e.message);}}
 return <section className="page"><header className="page-head"><h1>{ar?'طلبات تسليم المبيعات':'Sales fulfillment requests'}</h1></header><p>{ar?'أرسل المحاسب الفاتورة من SolaCount. الطلب لا يحجز مخزوناً ولا يسلم بضاعة. اعتمد المستودع ثم استخدم أمر البيع للحجز والتجهيز والتسليم الفعلي.':'The accountant sent this invoice from SolaCount. A request does not reserve or dispatch stock. Approve its warehouse, then use the sales order to reserve, prepare, and dispatch actual goods.'}</p>
 <nav aria-label={ar?'حالة طلبات التسليم':'Fulfillment status'} style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}>{[['active',ar?'النشطة':'Active'],['cancelled',ar?'الملغاة':'Cancelled'],['history',ar?'السجل':'History']].map(([value,label])=><button type="button" key={value} className={filter===value?'btn btn--primary':'btn'} aria-pressed={filter===value} onClick={()=>setParams({status:value})}>{label}</button>)}</nav>
 {error&&<div role="alert" className="banner banner--warn">{error}</div>}{query.isError?<div role="alert" className="banner banner--warn">{ar?'تعذر تحميل الطلبات. تحقق من صلاحياتك وأعد المحاولة.':'Requests could not be loaded. Check your access and retry.'}<button className="btn" onClick={()=>query.refetch()}>{ar?'إعادة المحاولة':'Retry'}</button></div>:query.isLoading?<p>{ar?'جار التحميل…':'Loading…'}</p>:rows.length===0?<div className="empty-state">{ar?'لا توجد طلبات تسليم في هذه القائمة.':'No fulfillment requests in this list.'}</div>:rows.map(r=><article className="panel" key={r.request_uuid} style={{marginBottom:16,overflowWrap:'anywhere'}}><h2>{r.number??(ar?'أُلغي قبل القبول':'Cancelled before acceptance')} · {ar?'الفاتورة':'Invoice'} {r.source_invoice_number??`#${r.source_invoice_id}`}</h2><p>{statuses[r.status]??(ar?'قيد المراجعة':'Needs review')}</p><div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>{ar?'الصنف':'Product'}</th><th>{ar?'المطلوب':'Requested'}</th><th>{ar?'تم تسليمه':'Dispatched'}</th><th>{ar?'الملغى بإشعار دائن':'Credited undelivered'}</th><th>{ar?'المتبقي':'Remaining'}</th></tr></thead><tbody>{r.lines.map(l=><tr key={l.id}><td>{l.item_name??l.item_id}</td><td>{l.requested_qty}</td><td>{l.fulfilled_qty}</td><td>{l.cancelled_quantity??'0.0000'}</td><td>{l.remaining_qty}</td></tr>)}</tbody></table></div>{r.shipments.map(s=><p key={s.id}><Link to={`/shipments/${s.id}`}>{s.shipment_number}</Link></p>)}{r.status==='pending'&&!r.approved_at&&canApprove&&<div><p>{ar?'اعتماد الطلب ينشئ أمر بيع للتجهيز فقط. لا يحجز أو يخصم مخزوناً.':'Approval creates a sales order for fulfillment only. It does not reserve or reduce stock.'}</p><WarehousePicker value={warehouses[r.id]??null} onChange={id=>setWarehouses(v=>({...v,[r.id]:id}))} autoSelectDefault/><button className="btn btn--primary" disabled={!warehouses[r.id]} onClick={()=>approve(r)}>{ar?'اعتماد طلب التسليم':'Approve fulfillment'}</button></div>}{r.sales_order_id&&r.status!=='cancelled'&&<Link className="btn btn--primary" to={`/sales-orders/${r.sales_order_id}`}>{ar?'فتح أمر البيع والتسليم':'Open sales order and dispatch'}</Link>}</article>)}
 </section>;
}
