import React,{useState} from 'react';
import {WarehousePicker} from '../components/pickers';
import {Link,useSearchParams} from 'react-router-dom';
import {api} from '../services/api';
import {useApiQuery} from '../hooks/useApiQuery';
import {useCan} from '../stores/meta';
import {useI18n} from '../i18n/context';
export default function ReceivingRequestsPage(){
 const {t,locale}=useI18n();const ar=locale==='ar'||document.documentElement.lang==='ar';const canValue=useCan('inventory.manage_adjustments');const canApprove=useCan('inventory.approve_purchase_orders');const [warehouses,setWarehouses]=useState({});const [error,setError]=useState('');
 async function approve(r){try{await api.approveReceivingRequest(r.id,{warehouse_id:warehouses[r.id]});query.refetch();setError('');}catch(e){setError(e.message);}}
 const [searchParams,setSearchParams]=useSearchParams();const status=['active','cancelled','history'].includes(searchParams.get('status'))?searchParams.get('status'):'active';const selected=searchParams.get('request');const selectedId=selected&&/^\d+$/.test(selected)?Number(selected):null;
 const query=useApiQuery(['receiving-requests',selectedId,status],()=>selectedId?api.receivingRequest(selectedId):api.receivingRequests(status),{fallback:[]});const data=selectedId&&query.data?[query.data]:(Array.isArray(query.data)?query.data:[]);
 const receiptStatuses={draft:ar?'مسودة':'Draft',posted:ar?'مؤكد':'Confirmed',reversed:ar?'معكوس':'Reversed'};
 const statuses={pending:ar?'بانتظار الاستلام':'Pending receiving',partial:ar?'استلام جزئي':'Partially received',complete:ar?'مكتمل':'Fully received',cancelled:ar?'ملغى':'Cancelled'};
 return <section className="page"><header className="page-head"><h1>{ar?'طلبات استلام المشتريات':'Purchase receiving requests'}</h1></header><p>{ar?'أرسل المحاسب هذه المشتريات من SolaCount. الطلب لا يضيف مخزوناً: تأكد من الكمية الفعلية والمستودع عند الاستلام.':'These purchases were sent by the accountant from SolaCount. A request adds no stock: confirm actual quantities and the warehouse when receiving.'}</p>
 <nav aria-label={ar?'حالة طلبات الاستلام':'Receiving request status'} style={{display:'flex',flexWrap:'wrap',gap:8,marginBottom:16}}>{[['active',ar?'النشطة':'Active'],['cancelled',ar?'الملغاة':'Cancelled'],['history',ar?'السجل':'History']].map(([value,label])=><button key={value} type="button" className={status===value?'btn btn--primary':'btn'} aria-pressed={status===value} onClick={()=>setSearchParams({status:value})}>{label}</button>)}</nav>
 {error&&<div role="alert" className="banner banner--warn">{error}</div>}{!canValue&&<div className="banner banner--warn">{ar?'اعتماد طلب الاستلام يسمح لك باستلامه في المستودع المخصص. الطلب غير المعتمد يحتاج اعتماد مسؤول المشتريات أولاً.':'An approved receiving request can be received in its assigned warehouse. An unapproved request needs approval by the purchasing approver first.'}</div>}
 {query.isError?<div role="alert" className="banner banner--warn">{ar?'تعذر فتح طلب الاستلام. تحقق من صلاحياتك ثم أعد المحاولة.':'The receiving request could not be opened. Check your access and try again.'}<button type="button" className="btn btn--sm" onClick={()=>query.refetch()}>{ar?'إعادة المحاولة':'Retry'}</button></div>:query.isLoading?<p>{ar?'جارٍ التحميل…':'Loading…'}</p>:data.length===0?<div className="banner">{ar?'لا توجد طلبات استلام. يمكن للمحاسب إرسال فاتورة شراء من SolaCount.':'No receiving requests yet. An accountant can send a purchase bill from SolaCount.'}</div>:data.map(r=><article key={r.history_uuid||r.id} className="card" style={{marginBottom:16,padding:16,overflowWrap:'anywhere'}}><h2>{r.number&&<>{r.number} · </>}{r.source_bill_number|| `${ar?'فاتورة':'Bill'} #${r.source_bill_id}`}</h2>{r.kind==='cancelled_before_delivery'&&<p>{ar?'أُلغي طلب الإرسال قبل وصوله إلى المخزون. لم يُنشأ طلب استلام أو إيصال بضائع.':'Sending was cancelled before Stock accepted it. No receiving request or goods receipt was created.'}</p>}<p>{statuses[r.status]} · {r.currency_code}</p><div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>{ar?'الصنف':'Product'}</th><th>{ar?'المطلوب':'Requested'}</th><th>{ar?'المستلم':'Received'}</th><th>{ar?'المتبقي':'Remaining'}</th></tr></thead><tbody>{r.lines.map(l=><tr key={l.id}><td>{l.item_name|| `${ar?'الصنف':'Product'} #${l.source_item_id}`}</td><td>{l.requested_qty}</td><td>{l.received_qty}</td><td>{l.remaining_qty}</td></tr>)}</tbody></table></div>{r.receipts.map(g=><p key={g.id}><Link to={`/goods-receipts/${g.id}`}>{g.number}</Link> · {receiptStatuses[g.status]??g.status}</p>)}{!r.approved&&r.status==='pending'&&canApprove&&<div><p>{ar?'اعتمد الاستلام وحدد المستودع. لا يضيف الاعتماد مخزوناً ولا يرحّل الفاتورة.':'Approve receiving and select the warehouse. Approval adds no stock and does not post the bill.'}</p><WarehousePicker autoSelectDefault defaultContext={`approve-${r.id}-${r.source_revision}`} value={Object.prototype.hasOwnProperty.call(warehouses,r.id)?warehouses[r.id]:(r.warehouse_id??null)} onChange={v=>setWarehouses(current=>({...current,[r.id]:v}))}/><button className="btn" disabled={!warehouses[r.id]} onClick={()=>approve(r)}>{ar?'اعتماد طلب الاستلام':'Approve receiving request'}</button></div>}{(canValue||r.approved)&&!['complete','cancelled'].includes(r.status)&&<Link className="btn btn--primary" to={`/goods-receipts/from-request/${r.id}`}>{ar?'استلام البضاعة':'Receive goods'}</Link>}</article>)}
 </section>;
}
