import React,{useState} from 'react';
import {WarehousePicker} from '../components/pickers';
import {Link} from 'react-router-dom';
import {api} from '../services/api';
import {useApiQuery} from '../hooks/useApiQuery';
import {useCan} from '../stores/meta';
import {useI18n} from '../i18n/context';
export default function ReceivingRequestsPage(){
 const {t,locale}=useI18n();const ar=locale==='ar'||document.documentElement.lang==='ar';const canValue=useCan('inventory.manage_adjustments');const canApprove=useCan('inventory.approve_purchase_orders');const [warehouses,setWarehouses]=useState({});const [error,setError]=useState('');
 async function approve(r){try{await api.approveReceivingRequest(r.id,{warehouse_id:warehouses[r.id]});query.refetch();setError('');}catch(e){setError(e.message);}}
 const query=useApiQuery(['receiving-requests'],()=>api.receivingRequests(),{fallback:[]});const data=Array.isArray(query.data)?query.data:(query.data?.data??[]);
 const receiptStatuses={draft:ar?'مسودة':'Draft',posted:ar?'مؤكد':'Confirmed',reversed:ar?'معكوس':'Reversed'};
 const statuses={pending:ar?'بانتظار الاستلام':'Pending receiving',partial:ar?'استلام جزئي':'Partially received',complete:ar?'مكتمل':'Fully received',cancelled:ar?'ملغى':'Cancelled'};
 return <section className="page"><header className="page-head"><h1>{ar?'طلبات استلام المشتريات':'Purchase receiving requests'}</h1></header><p>{ar?'أرسل المحاسب هذه المشتريات من SolaCount. الطلب لا يضيف مخزوناً: تأكد من الكمية الفعلية والمستودع عند الاستلام.':'These purchases were sent by the accountant from SolaCount. A request adds no stock: confirm actual quantities and the warehouse when receiving.'}</p>
 {error&&<div role="alert" className="banner banner--warn">{error}</div>}{!canValue&&<div className="banner banner--warn">{ar?'اعتماد طلب الاستلام يسمح لك باستلامه في المستودع المخصص. الطلب غير المعتمد يحتاج اعتماد مسؤول المشتريات أولاً.':'An approved receiving request can be received in its assigned warehouse. An unapproved request needs approval by the purchasing approver first.'}</div>}
 {query.isLoading?<p>{ar?'جارٍ التحميل…':'Loading…'}</p>:data.length===0?<div className="banner">{ar?'لا توجد طلبات استلام. يمكن للمحاسب إرسال فاتورة شراء من SolaCount.':'No receiving requests yet. An accountant can send a purchase bill from SolaCount.'}</div>:data.map(r=><article key={r.id} className="card" style={{marginBottom:16,padding:16,overflowWrap:'anywhere'}}><h2>{r.number} · {r.source_bill_number|| (ar?'فاتورة مسودة':'Draft bill')}</h2><p>{statuses[r.status]} · {r.currency_code}</p><div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>{ar?'الصنف':'Product'}</th><th>{ar?'المطلوب':'Requested'}</th><th>{ar?'المستلم':'Received'}</th><th>{ar?'المتبقي':'Remaining'}</th></tr></thead><tbody>{r.lines.map(l=><tr key={l.id}><td>{l.item_name}</td><td>{l.requested_qty}</td><td>{l.received_qty}</td><td>{l.remaining_qty}</td></tr>)}</tbody></table></div>{r.receipts.map(g=><p key={g.id}><Link to={`/goods-receipts/${g.id}`}>{g.number}</Link> · {receiptStatuses[g.status]??g.status}</p>)}{!r.approved&&r.status==='pending'&&canApprove&&<div><p>{ar?'اعتمد الاستلام وحدد المستودع. لا يضيف الاعتماد مخزوناً ولا يرحّل الفاتورة.':'Approve receiving and select the warehouse. Approval adds no stock and does not post the bill.'}</p><WarehousePicker value={warehouses[r.id]??null} onChange={v=>setWarehouses({...warehouses,[r.id]:v})}/><button className="btn" disabled={!warehouses[r.id]} onClick={()=>approve(r)}>{ar?'اعتماد طلب الاستلام':'Approve receiving request'}</button></div>}{(canValue||r.approved)&&!['complete','cancelled'].includes(r.status)&&<Link className="btn btn--primary" to={`/goods-receipts/from-request/${r.id}`}>{ar?'استلام البضاعة':'Receive goods'}</Link>}</article>)}
 </section>;
}
