import React,{useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {api} from '../services/api';
import {useApiQuery} from '../hooks/useApiQuery';
import {useCan} from '../stores/meta';
import {useI18n} from '../i18n/context';
import {ConfirmModal} from '../components/ui';
import {returnLines} from '../domain/supplierReturnSelection.mjs';

export default function SupplierReturnsPage(){
 const {locale}=useI18n();const ar=locale==='ar';const text=(en,arabic)=>ar?arabic:en;
 const can=useCan();const permitted=can('inventory.manage_purchase_returns');const [params,setParams]=useSearchParams();
 const id=params.get('return');const receipt=params.get('receipt')||'';
 const [quantities,setQuantities]=useState({});const [reason,setReason]=useState('');const [date,setDate]=useState(new Date().toLocaleDateString('en-CA'));const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [uncertain,setUncertain]=useState(false);const [confirmation,setConfirmation]=useState(null);
 const list=useApiQuery(['supplier-returns'],()=>api.supplierReturns({per_page:50}));
 const receipts=useApiQuery(['supplier-return-receipts'],()=>api.goodsReceipts({status:'posted',per_page:100}),{enabled:!id});
 const source=useApiQuery(['supplier-return-source',receipt],()=>api.supplierReturnSource(receipt),{enabled:!!receipt&&!id});
 const detail=useApiQuery(['supplier-return',id],()=>api.supplierReturn(id),{enabled:!!id});
 const document=detail.data?.supplier_return;const rows=Array.isArray(list.data)?list.data:list.data?.data||[];const receiptRows=Array.isArray(receipts.data)?receipts.data:receipts.data?.data||[];
 const state={draft:text('Draft','مسودة'),posted:text('Returned','تم الإرجاع'),reversed:text('Reversed','معكوس')};
 async function mutate(action){if(busy||uncertain)return;setBusy(true);setError('');try{const result=await action();setConfirmation(null);await list.refetch();if(id)await detail.refetch();return result;}catch(e){setError(e.message||text('Review the source receipt and try again.','راجع سند الاستلام ثم حاول مجدداً.'));if(e.outcomeUnknown)setUncertain(true);}finally{setBusy(false);}}
 async function save(){let lines;try{lines=returnLines(source.data?.lines||[],quantities);if(!lines.length)throw Error();}catch{setError(text('Enter a valid return quantity, within each available receipt quantity.','أدخل كمية إرجاع صحيحة لا تتجاوز الكمية المتاحة لكل سطر.'));return;}
 const result=await mutate(()=>api.createSupplierReturn({goods_receipt_id:Number(receipt),return_date:date,reason,lines}));if(result?.data?.id)setParams({return:String(result.data.id)});}
 return <section className="page" dir={ar?'rtl':'ltr'}><header className="page-head"><h1>{text('Supplier returns','مرتجعات الموردين')}</h1><button type="button" className="btn" disabled={busy||uncertain} onClick={()=>{setParams({});setReason('');setQuantities({});}}>{text('Return history','سجل المرتجعات')}</button></header>
 <p>{text('Choose a confirmed receipt. Saving a draft changes no stock. Posting records the actual goods returned; supplier credit and refunds are reviewed separately.','اختر سند استلام مؤكداً. حفظ المسودة لا يغيّر المخزون. التأكيد يسجل البضاعة المعادة فعلياً؛ يُراجع إشعار المورد واسترداد المبلغ بشكل مستقل.')}</p>
 {error&&<div role="alert" className="banner banner--warn">{error}</div>}{uncertain&&<p role="alert">{text('The result is not yet known. Refresh the return history and check the saved document before trying another action.','نتيجة العملية غير مؤكدة. حدّث سجل المرتجعات وتحقق من المستند المحفوظ قبل تنفيذ عملية أخرى.')}</p>}
 {(list.isError||source.isError||detail.isError||receipts.isError)&&<p role="alert">{text('Unable to load the permitted source documents. Refresh this page or ask your administrator to review access.','تعذر تحميل المستندات المسموح بها. حدّث الصفحة أو اطلب من المسؤول مراجعة الصلاحيات.')}</p>}
 {id?(document?<article className="card"><h2>{document.return_number}</h2><p>{state[document.status]||text('Needs review','بحاجة للمراجعة')} · {document.goods_receipt?.grn_number}</p><p>{document.reason}</p>{(document.lines||[]).map(line=><p key={line.id}>{line.item?.name} · {line.entered_qty} · {text('Warehouse','المستودع')} #{line.warehouse_id}</p>)}
 {permitted&&detail.data.can_manage&&!uncertain&&<div style={{display:'flex',flexWrap:'wrap',gap:8}}>{document.status==='draft'&&<button type="button" disabled={busy} className="btn btn--primary" onClick={()=>setConfirmation('post')}>{text('Confirm physical return','تأكيد الإرجاع الفعلي')}</button>}{document.status==='posted'&&!document.reversed_at&&<><label>{text('Reversal reason','سبب العكس')}<input value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></label><button type="button" className="btn" disabled={busy||reason.trim().length<3} onClick={()=>setConfirmation('reverse')}>{text('Reverse return','عكس الإرجاع')}</button></>}</div>}</article>:<p>{text('Loading…','جارٍ التحميل…')}</p>):<>
 {permitted&&<form className="card" onSubmit={e=>{e.preventDefault();save();}}><h2>{text('New supplier return','إرجاع جديد للمورد')}</h2><label>{text('Confirmed receipt','سند الاستلام المؤكد')}<select required value={receipt} disabled={busy||uncertain} onChange={e=>{setParams(e.target.value?{receipt:e.target.value}:{});setQuantities({});}}><option value="">{text('Choose a receipt','اختر سند استلام')}</option>{receiptRows.filter(r=>r.status==='posted'&&!r.reversed_at).map(r=><option key={r.id} value={r.id}>{r.grn_number}</option>)}</select></label>
 {source.data&&<><p>{source.data.receipt_number} · {text('Original receiving warehouse','مستودع الاستلام الأصلي')} #{source.data.warehouse_id}</p>{source.data.lines.map(line=><div key={line.source_stock_ledger_id} style={{display:'flex',flexWrap:'wrap',gap:12,alignItems:'center',marginBlock:12}}><span style={{flex:'1 1 220px'}}>{line.item_name} · {line.unit_label} · {text('Available','المتاح')} {line.remaining_entered_quantity}{[['lot_id','Lot','دفعة'],['serial_id','Serial','تسلسلي'],['bin_id','Bin','موقع']].map(([key,en,arabic])=>line[key]?<small key={key} style={{display:'block'}}>{text(en,arabic)} #{line[key]}</small>:null)}</span><label>{text('Return quantity','كمية الإرجاع')}<input type="number" min="0" step="0.0001" max={line.remaining_entered_quantity} value={quantities[line.source_stock_ledger_id]??'0'} disabled={busy||uncertain} onChange={e=>setQuantities({...quantities,[line.source_stock_ledger_id]:e.target.value})}/></label></div>)}{!source.data.lines.length&&<p>{text('No remaining receipt quantities can be returned.','لا توجد كميات متبقية قابلة للإرجاع.')}</p>}</>}
 <label>{text('Return date','تاريخ الإرجاع')}<input type="date" required value={date} disabled={busy||uncertain} onChange={e=>setDate(e.target.value)}/></label><label>{text('Reason','السبب')}<textarea required minLength={3} maxLength={2000} value={reason} disabled={busy||uncertain} onChange={e=>setReason(e.target.value)}/></label><button className="btn btn--primary" type="submit" disabled={busy||uncertain||!source.data?.can_manage||!source.data?.lines.length}>{busy?text('Saving…','جارٍ الحفظ…'):text('Save draft','حفظ المسودة')}</button></form>}
 <div style={{display:'grid',gap:12}}>{rows.map(r=><article className="card" key={r.id}><button className="btn" type="button" disabled={busy} onClick={()=>setParams({return:String(r.id)})}>{r.return_number}</button><p>{r.goods_receipt?.grn_number} · {state[r.status]||text('Needs review','بحاجة للمراجعة')}</p></article>)}</div></>}
 <ConfirmModal open={!!confirmation} title={confirmation==='post'?text('Confirm physical return','تأكيد الإرجاع الفعلي'):text('Reverse return','عكس الإرجاع')} message={confirmation==='post'?text('Confirm these goods are leaving the original warehouse now. Inventory value follows the configured costing policy, not the original purchase price.','أكد خروج هذه البضاعة من المستودع الأصلي الآن. تتبع قيمة المخزون سياسة التكلفة المعتمدة، وليس سعر الشراء الأصلي.'):text('This reverses this return only. Financial credits must be reviewed separately.','يعكس هذا الإرجاع فقط. يجب مراجعة الإشعارات المالية بشكل مستقل.')} confirmLabel={text('Confirm','تأكيد')} onCancel={()=>{if(!busy)setConfirmation(null);}} onConfirm={()=>mutate(()=>confirmation==='post'?api.postSupplierReturn(id):api.reverseSupplierReturn(id,{reason}))}/>
 </section>;
}
