<?php
namespace App\Services\Sales;
use App\Models\Tenant\{Customer,FulfillmentRequest,IntegrationDocumentLifecycleMapping,IntegrationMasterDataMapping,IntegrationOrganizationMapping,IntegrationOutboxEvent,IntegrationSetting,Item,SalesDocumentOutbox,SalesOrder,SalesOrderLine,Shipment,Unit};
use App\Services\Integration\{ApprovedFinanceIntegrationEntitlement,FinanceOnboardingReadiness,IntegrationSafetyHold,SolaBooksOutboxDeliveryService,SolaStockJournalContract};
use App\Services\Purchasing\ReceivingRequestService;
use App\Services\Stock\Support\Decimal;
use Illuminate\Support\Facades\{DB,Schema};
use Illuminate\Support\Str;
/** Document handoff is durable local data; delivery never runs inside a shipment transaction. */
final class ShipmentHandoffService
{
 private function mapped($m,string$type,?int$id):?int {if(!$id)return null;return IntegrationMasterDataMapping::query()->where('organization_mapping_uuid',$m->mapping_uuid)->where('central_client_id',$m->central_client_id)->where('central_organization_id',$m->central_organization_id)->where('finance_organization_id',$m->finance_organization_id)->where('solastock_organization_id',$m->solastock_organization_id)->where('entity_type',$type)->where('solastock_record_id',(string)$id)->where('status','verified')->whereNull('conflict_code')->whereNull('error_state')->where('solastock_archived',false)->where('solabooks_archived',false)->value('solabooks_record_id');}
 public function record(Shipment$s,bool$reverse=false):?SalesDocumentOutbox {
  $m=IntegrationOrganizationMapping::query()->where('solastock_organization_id',$s->organization_id)->where('tenant_database_identity',DB::connection('tenant')->getDatabaseName())->whereIn('status',['verified','verified_hold'])->whereIn('activation_state',['active','maintenance_hold'])->first();
  $setting=IntegrationSetting::query()->where('organization_id',$s->organization_id)->where('integration','solabooks')->first();if(!$m||!in_array($setting?->mode,['active','paused','connected_readonly','connected_pending_mapping'],true))return null;
  $life=IntegrationDocumentLifecycleMapping::query()->where('organization_mapping_uuid',$m->mapping_uuid)->where('source_document_type','shipment')->where('source_document_id',(string)$s->id)->firstOrFail();
  $key='sales:shipment:'.$life->mapping_uuid.':'.($reverse?'reversed':'confirmed');if($e=SalesDocumentOutbox::query()->where('source_key',$key)->first())return$e;
  $order=SalesOrder::query()->whereKey($s->sales_order_id)->firstOrFail();$request=FulfillmentRequest::query()->where('sales_order_id',$order->id)->first();
  $journal=IntegrationOutboxEvent::query()->where('organization_id',$s->organization_id)->where('event_type','shipment.posted')->where('aggregate_id',$s->id)->firstOrFail();$currency=(array)data_get($journal->payload,'currency',[]);$missing=[];$customer=$this->mapped($m,'customer',$order->customer_id);if(!$customer)$missing[]='customer_mapping';$lines=[];$s->loadMissing('lines');
  foreach($s->lines as$l){if(!Decimal::gt((string)$l->quantity,'0'))continue;$factor=(string)($l->unit_conversion_factor?:'1');$source=$l->sales_order_line_id?SalesOrderLine::query()->where('sales_order_id',$order->id)->whereKey($l->sales_order_line_id)->first():null;$item=$this->mapped($m,'item',$l->item_id);$unit=$this->mapped($m,'unit',$l->entered_unit_id);if(!$item)$missing[]='item_mapping:'.$l->id;if(!$unit)$missing[]='unit_mapping:'.$l->id;if(!$source)$missing[]='selling_price:'.$l->id;
   $lines[]=['source_line_id'=>(string)$l->id,'source_invoice_line_id'=>$request?->lines()->where('sales_order_line_id',$l->sales_order_line_id)->value('source_line_id'),'sales_order_line_id'=>$l->sales_order_line_id,'item_id'=>$l->item_id,'item_name'=>Item::query()->find($l->item_id)?->name,'item_sku'=>Item::query()->find($l->item_id)?->sku,'unit_id'=>$l->entered_unit_id,'unit_label'=>Unit::query()->find($l->entered_unit_id)?->code,'item_external_id'=>$item,'unit_external_id'=>$unit,'quantity'=>Decimal::qty(Decimal::div((string)$l->quantity,$factor)),'base_quantity'=>(string)$l->quantity,'unit_conversion_factor'=>$factor,'unit_price'=>$source?Decimal::cost(Decimal::mul((string)$source->unit_price,$factor)):null,'discount_rate'=>$source?(string)$source->discount_rate:null,'stock_tax_code'=>$source?->tax_code,'stock_tax_rate'=>$source?(string)$source->tax_rate:null];
  }
  $uuid=(string)Str::uuid();$payload=['source_app'=>'solastock','schema_version'=>'sales.v1','contract_version'=>SolaStockJournalContract::VERSION,'event_uuid'=>$uuid,'event_type'=>$reverse?'sales.shipment.reversed':'sales.shipment.confirmed','external_source_key'=>$key,'inventory_organization_id'=>$s->organization_id,'finance_organization_id'=>$m->finance_organization_id,'identity'=>['central_client_id'=>$m->central_client_id,'central_organization_id'=>$m->central_organization_id,'finance_organization_id'=>$m->finance_organization_id,'inventory_organization_id'=>$m->solastock_organization_id,'integration_mapping_id'=>$m->id,'organization_mapping_uuid'=>$m->mapping_uuid,'signing_key_id'=>(string)data_get($setting->meta,'signing_key_id')],'shipment'=>['mapping_uuid'=>$life->mapping_uuid,'id'=>$s->id,'number'=>$s->shipment_number,'date'=>$s->ship_date?->format('Y-m-d'),'request_uuid'=>$request?->request_uuid,'fulfillment_request'=>$request?app(FulfillmentRequestService::class)->status($request):null,'source_invoice_id'=>$request?->source_invoice_id,'sales_order_id'=>$order->id,'customer_id'=>$order->customer_id,'customer_name'=>Customer::query()->find($order->customer_id)?->name,'customer_external_id'=>$customer,'currency_code'=>$currency['code']??$m->base_currency_code,'base_currency_code'=>$m->base_currency_code,'exchange_rate'=>$currency['exchange_rate']??'1','exchange_rate_date'=>$currency['rate_date']??$s->ship_date?->format('Y-m-d'),'accounting_source_key'=>$journal->idempotency_key,'journal_idempotency_key'=>$journal->idempotency_key,'lines'=>$lines,'missing_information'=>array_values(array_unique($missing))]];
  return SalesDocumentOutbox::create(['organization_id'=>$s->organization_id,'organization_mapping_uuid'=>$m->mapping_uuid,'source_key'=>$key,'event_uuid'=>$uuid,'event_type'=>$payload['event_type'],'payload'=>$payload,'payload_hash'=>hash('sha256',SolaStockJournalContract::canonicalJson($payload))]);
 }
 public function deliverDue(int$limit=2):int {
  if(!Schema::connection('tenant')->hasTable('sales_document_outbox'))return 0;$count=0;
  for($i=0;$i<min(2,$limit);$i++){
   $m=app(ReceivingRequestService::class)->mapping();app(ApprovedFinanceIntegrationEntitlement::class)->assertApproved($m);app(IntegrationSafetyHold::class)->assertDeliveryEnabledFor((int)$m->solastock_organization_id);app(FinanceOnboardingReadiness::class)->assertComplete((int)$m->solastock_organization_id);
   $event=DB::connection('tenant')->transaction(function(){ $e=SalesDocumentOutbox::query()->where('attempts','<',40)->where(fn($q)=>$q->where('status','pending')->orWhere(fn($q)=>$q->where('status','retry')->where('next_attempt_at','<=',now()))->orWhere(fn($q)=>$q->where('status','processing')->where('lease_expires_at','<=',now())))->orderBy('id')->lockForUpdate()->first();if(!$e)return null;$e->update(['status'=>'processing','lease_token'=>(string)Str::uuid(),'lease_expires_at'=>now()->addSeconds(60),'attempts'=>$e->attempts+1]);return$e;});if(!$event)break;
   try{$result=app(SolaBooksOutboxDeliveryService::class)->sendSalesDocument($event);}catch(\Throwable$e){report($e);$result=['successful'=>false,'data'=>[]];}
   DB::connection('tenant')->transaction(function()use($event,$result){$e=SalesDocumentOutbox::query()->whereKey($event->id)->lockForUpdate()->firstOrFail();if($e->lease_token!==$event->lease_token)return;$ok=$result['successful'];$e->update(['status'=>$ok?'sent':($e->attempts>=40?'intervention':'retry'),'response'=>$ok?$result['data']:null,'lease_token'=>null,'lease_expires_at'=>null,'next_attempt_at'=>$ok?null:now()->addSeconds(min(3600,30*2**min(7,$e->attempts))),'last_error'=>$ok?null:__('inventory.purchasing.delivery_pending')]);});$count++;
  }return$count;
 }
}
