<?php

return [
    'application' => 'SolaStock',
    'app_key' => 'solastock',
    'schema_version' => 1,
    'migration_group' => [
        'id' => 'solastock.inventory',
        'order' => 300,
        'path' => 'database/migrations/tenant',
        'after' => ['shared-core', 'solacount'],
    ],
    'canonical_solacount_candidate' => [
        'id' => 'solacount-sv2-b0004-362a2189',
        'root' => '/var/www/html/solavel-finance/resources/spsb/candidates/solacount-sv2-b0004-362a2189',
        'manifest_sha256' => '0109f334eb97eb738053c39b5974c58fe8b6dd17351ce52f8b7ec7a81b3bb55e',
        'runtime_baseline' => '/var/www/html/solavel-finance/resources/spsb/runtime/solacount-sv2-b0004-362a2189/baseline.sql',
        'runtime_baseline_sha256' => '99dcde87455969d216e7c264c004ac5b4ec650d1bbe66239c43d17b35a8a508c',
    ],
    'ownership' => [
        'shared_core_contributor' => [
            'migrations',
            'tenant_entitlements_snapshots',
        ],
        'integration_contract' => [
            'integration_account_mappings',
            'integration_connection_wizard_audits',
            'integration_connection_wizard_decisions',
            'integration_connection_wizard_runs',
            'integration_dead_letter_reviews',
            'integration_document_lifecycle_audits',
            'integration_document_lifecycle_links',
            'integration_document_lifecycle_mappings',
            'integration_historical_repair_attempt_audits',
            'integration_historical_repair_batches',
            'integration_mapping_audits',
            'integration_mapping_discovery_results',
            'integration_mapping_discovery_runs',
            'integration_master_data_mappings',
            'integration_organization_mappings',
            'integration_outbox_events',
            'integration_outbox_transition_audits',
            'integration_settings',
            'integration_tax_mappings',
            'integration_transport_worker_heartbeats',
            'item_integration_mappings',
        ],
        'solastock_owned' => [
            'cost_layer_consumptions',
            'cost_layers',
            'dashboard_layouts',
            'goods_receipt_lines',
            'goods_receipts',
            'inventory_alerts',
            'inventory_audit_logs',
            'inventory_currency_rates',
            'inventory_custom_roles',
            'inventory_customers',
            'inventory_purchase_orders',
            'inventory_reversals',
            'inventory_sales_orders',
            'inventory_scheduled_reports',
            'inventory_settings',
            'inventory_suppliers',
            'inventory_user_role_assignments',
            'inventory_user_warehouses',
            'item_attachments',
            'item_barcodes',
            'item_brands',
            'item_images',
            'item_categories',
            'item_variants',
            'items',
            'lots',
            'opening_stock_entries',
            'opening_stock_entry_lines',
            'pack_lines',
            'packs',
            'pick_list_lines',
            'pick_lists',
            'pos_sale_consumption_lines',
            'pos_sale_consumptions',
            'purchase_order_backorders',
            'purchase_order_lines',
            'recall_actions',
            'recall_lines',
            'recalls',
            'reservations',
            'sales_order_lines',
            'sales_return_lines',
            'sales_returns',
            'serial_numbers',
            'shipment_lines',
            'shipments',
            'stock_adjustment_lines',
            'stock_adjustments',
            'stock_balances',
            'stock_count_lines',
            'stock_counts',
            'stock_ledger',
            'stock_transfer_lines',
            'stock_transfers',
            'supplier_price_lists',
            'unit_conversions',
            'units',
            'warehouse_bins',
            'warehouse_images',
            'warehouse_reorder_rules',
            'warehouse_zones',
            'warehouses',
        ],
    ],
    // These names are authoritative in SolaCount or Shared Core. They may exist
    // in a canonical tenant, but SolaStock must never contribute their schema.
    'forbidden_foreign_authority' => [
        'currencies',
        'customers',
        'inventory_cells',
        'inventory_items',
        'inventory_locations',
        'inventory_movements',
        'inventory_stocks',
        'inventory_units',
        'inventory_valuations',
        'inventory_zones',
        'organizations',
        'suppliers',
        'taxes',
        'users',
    ],
    // These names exist before SolaStock in the canonical lifecycle and must
    // byte-match the SolaStock reference schema before any SolaStock migration.
    'exact_preexisting_contracts' => [
        'integration_document_lifecycle_audits',
        'integration_document_lifecycle_links',
        'integration_document_lifecycle_mappings',
        'integration_historical_repair_attempt_audits',
        'integration_historical_repair_batches',
        'integration_mapping_audits',
        'integration_mapping_discovery_results',
        'integration_mapping_discovery_runs',
        'integration_master_data_mappings',
        'integration_organization_mappings',
        'tenant_entitlements_snapshots',
    ],
    'integration_invariants' => [
        'receiver_contract' => 'solastock-journal.v2',
        'base_currency' => 'JOD',
        'delivery_enabled' => false,
        'pending_event_replay_enabled' => false,
        'historical_repair_enabled' => false,
        'legacy_inventory_writes_blocked' => true,
        'preserved_statuses' => ['pending', 'ignored', 'untrusted'],
    ],
];
