<?php
$loader=require($argv[1]??throw new RuntimeException('Native vendor required')).'/autoload.php';$loader->addClassMap([App\Services\Sales\FulfillmentRequestService::class=>dirname(__DIR__,2).'/app/Services/Sales/FulfillmentRequestService.php']);
$app=new Illuminate\Foundation\Application(dirname(__DIR__,2));$capsule=new Illuminate\Database\Capsule\Manager($app);$capsule->addConnection(['driver'=>'sqlite','database'=>':memory:','prefix'=>''],'tenant');$capsule->setAsGlobal();$capsule->bootEloquent();$app->instance('db',$capsule->getDatabaseManager());Illuminate\Support\Facades\Facade::setFacadeApplication($app);$db=$capsule->getConnection('tenant');$app->instance('translator',new Illuminate\Translation\Translator(new Illuminate\Translation\ArrayLoader,'en'));
$db->statement('CREATE TABLE invoices(id INTEGER,organization_id INTEGER)');$db->statement('CREATE TABLE finance_sales_requests(id INTEGER,organization_id INTEGER,organization_mapping_uuid TEXT,invoice_id INTEGER,request_uuid TEXT,command TEXT,source_revision TEXT,invoice_journal_id INTEGER)');$db->statement('CREATE TABLE journal_entries(id INTEGER,organization_id INTEGER,source_type TEXT,source_id INTEGER,status TEXT,voided_at TEXT,deleted_at TEXT)');
$db->table('invoices')->insert(['id'=>13,'organization_id'=>1]);$db->table('finance_sales_requests')->insert(['id'=>1,'organization_id'=>1,'organization_mapping_uuid'=>'mapped-org','invoice_id'=>13,'request_uuid'=>'request-13','command'=>'upsert','source_revision'=>'saved-native-revision','invoice_journal_id'=>96]);
// Independent native Finance model FQCN, not copied from the tested service.
$db->table('journal_entries')->insert(['id'=>96,'organization_id'=>1,'source_type'=>'App\Models\Invoice','source_id'=>13,'status'=>'posted']);
$service=new App\Services\Sales\FulfillmentRequestService(new App\Tenancy\OrganizationContext);$method=new ReflectionMethod($service,'lockFinanceCommand');$method->setAccessible(true);$map=(object)['finance_organization_id'=>1,'mapping_uuid'=>'mapped-org'];$p=['source_invoice_id'=>13,'request_uuid'=>'request-13','source_revision'=>'saved-native-revision','source_status'=>'posted','posted_invoice_journal_id'=>96];$method->invoke($service,$map,$p,'upsert');echo "PASS native source FQCN exact journal\n";
foreach([['source_id'=>14],['organization_id'=>2],['voided_at'=>'2026-10-07'],['source_type'=>'App\Models\Bill']]as$c){$db->table('journal_entries')->where('id',96)->update($c);try{$method->invoke($service,$map,$p,'upsert');throw new RuntimeException('Invalid source admitted');}catch(Symfony\Component\HttpKernel\Exception\HttpException $e){if($e->getStatusCode()!==409)throw $e;}echo "PASS wrong source/org/void/type denied409\n";$db->table('journal_entries')->where('id',96)->update(['organization_id'=>1,'source_id'=>13,'voided_at'=>null,'source_type'=>'App\Models\Invoice']);}
$p['source_revision']='changed';try{$method->invoke($service,$map,$p,'upsert');throw new RuntimeException('Changed revision admitted');}catch(Symfony\Component\HttpKernel\Exception\HttpException $e){if($e->getStatusCode()!==409)throw $e;}echo "PASS stale revision denied409\n";
