#!/usr/bin/env python3
"""Generate dark-theme overrides for rules that hard-code light-theme colours.

Many feature stylesheets were written for the light theme only (white cards,
pale tinted banners, near-black text). This script finds those declarations
and emits `[data-theme="dark"]` counterparts mapped onto the theme tokens:

  * light backgrounds  -> surface tokens, or the matching soft tint by hue
  * dark text colours  -> text tokens, or a light tint of the same hue
  * light borders      -> the line token, or a translucent tint by hue

Run from the repository root; it rewrites the generated block at the end of
each stylesheet in place:

    python3 scripts/generate-dark-overrides.py
"""
import colorsys
import re
from pathlib import Path

FILES = [
    Path('resources/js/solastock/styles/solastock.css'),
    Path('resources/js/solastock/components/FinanceReadiness.css'),
]
START = '/* ==== dark-theme overrides (generated by scripts/generate-dark-overrides.py) ==== */'
END = '/* ==== end generated dark-theme overrides ==== */'

# Selectors that are dark in both themes or sit on a strong colour already.
SKIP = re.compile(r'data-theme|\.side-|\.nav-item|\.sidebar|\.ai-|\.floor-|\.tk-|\.app\b|\.side-link|\.onb-step--done|gallery|:root')

HEX = re.compile(r'#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b')
PROPS = ('background', 'background-color', 'color', 'border', 'border-color', 'border-top', 'border-bottom',
         'border-inline-start', 'border-left', 'border-right')

TINT_BG = {'amber': 'var(--amber-tint)', 'green': 'var(--green-soft)', 'red': 'var(--red-soft)',
           'blue': 'var(--blue-soft)', 'violet': 'var(--violet-soft)'}
TINT_TEXT = {'amber': 'var(--amber-soft)', 'green': '#5fd3a2', 'red': '#f19a9a', 'blue': '#8fb6f0', 'violet': '#b3a9f7'}
TINT_LINE = {'amber': 'rgba(224,153,33,.32)', 'green': 'rgba(31,157,107,.32)', 'red': 'rgba(224,81,81,.32)',
             'blue': 'rgba(59,125,224,.32)', 'violet': 'rgba(124,109,240,.32)'}


def rgb(hex_value):
    h = hex_value.lstrip('#')
    if len(h) == 3:
        h = ''.join(c * 2 for c in h)
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


def family(r, g, b):
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    if s < 0.18 or (max(r, g, b) - min(r, g, b)) < 0.06:
        return None
    deg = h * 360
    if deg < 18 or deg >= 330:
        return 'red'
    if deg < 65:
        return 'amber'
    if deg < 170:
        return 'green'
    if deg < 255:
        return 'blue'
    return 'violet'


def lum(r, g, b):
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def map_value(prop, value):
    """Return the dark replacement for one declaration value, or None."""
    important = '!important' if '!important' in value else ''
    value_clean = value.replace('!important', '').strip()
    if value_clean in ('white', '#fff', '#ffffff') and prop.startswith('background'):
        return 'var(--surface)' + important
    # Only colours written literally count: a `var(--token, #fallback)` already
    # follows the theme because every token it names is defined in both themes.
    parts = re.split(r'(var\([^()]*\))', value_clean)
    touched = False
    for i, part in enumerate(parts):
        if part.startswith('var('):
            continue
        for c in HEX.findall(part):
            r, g, b = rgb(c)
            fam = family(r, g, b)
            L = lum(r, g, b)
            if prop.startswith('background'):
                if L < 0.80:
                    continue
                repl = TINT_BG[fam] if fam else ('var(--surface)' if L > 0.985 else 'var(--surface-2)')
            elif prop == 'color':
                if L > 0.55:
                    continue
                repl = TINT_TEXT[fam] if fam else ('var(--text)' if L < 0.22 else 'var(--text-2)')
            else:  # borders
                if L < 0.70:
                    continue
                repl = TINT_LINE[fam] if fam else 'var(--line)'
            part = re.sub('#' + c + r'\b', repl, part, count=1)
            touched = True
        parts[i] = part
    changed = ''.join(parts)
    if not touched:
        return None
    return changed + (' ' + important if important else '')


def rules(css):
    """Yield (selector, body) for every plain rule, including those nested in @media."""
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    for m in re.finditer(r'([^{}@]+)\{([^{}]*)\}', css):
        selector = m.group(1).strip()
        if not selector or selector.startswith(('from', 'to')) or re.match(r'^[\d.%\s,]+$', selector):
            continue
        yield selector, m.group(2)


def generate(css):
    css = css.split(START)[0].rstrip() + '\n'
    out = []
    for selector, body in rules(css):
        if SKIP.search(selector):
            continue
        decls = []
        for decl in body.split(';'):
            if ':' not in decl:
                continue
            prop, value = decl.split(':', 1)
            prop = prop.strip().lower()
            if prop not in PROPS:
                continue
            mapped = map_value(prop, value)
            if mapped:
                decls.append(f'{prop}:{mapped}')
        if decls:
            scoped = ','.join('[data-theme="dark"] ' + s.strip() for s in selector.split(',') if s.strip())
            out.append(f'{scoped}{{{";".join(decls)}}}')
    return css + '\n' + START + '\n' + '\n'.join(out) + '\n' + END + '\n', len(out)


if __name__ == '__main__':
    for path in FILES:
        text, count = generate(path.read_text())
        path.write_text(text)
        print(f'{path}: {count} dark overrides')
