<?php
namespace App\Services\Purchasing;
use App\Models\Tenant\{GoodsReceipt,IntegrationDocumentLifecycleMapping,IntegrationMasterDataMapping,IntegrationOrganizationMapping,IntegrationOutboxEvent};
use App\Services\Integration\SolaStockJournalContract;
use App\Services\Stock\Support\Decimal;
use App\Tenancy\OrganizationContext;
use Illuminate\Support\Facades\DB;
use Ramsey\Uuid\Uuid;
/** Immutable value-only provenance. Construction rechecks native facts under their lifecycle locks. */
final readonly class LandedCostAllocationAuthority {
 private function __construct(private array $facts,private array $sources,private array $proof,private int $stockOrg,private int $financeOrg,private int $scale){}
 public static function fromLockedNativeProvenance(array $identity,array $proof,IntegrationOrganizationMapping $mapping,string $action,int $actor):self {
  $db=DB::connection('tenant');$org=app(OrganizationContext::class)->idOrFail();abort_unless($db->transactionLevel()>0&&in_array($action,['prepare','apply','reverse','release','status'],true)&&$actor>0,403);
  abort_unless(($proof['operation']??null)===$action&&(int)($proof['actor_id']??0)===$actor&&($proof['operation_uuid']??null)===$identity['operation_uuid']&&($proof['organization_mapping_uuid']??null)===$mapping->mapping_uuid&&(int)($proof['finance_organization_id']??0)===(int)$mapping->finance_organization_id,403);
  $bill=$db->table('bills')->where('organization_id',$mapping->finance_organization_id)->where('id',$identity['source_bill_id'])->lockForUpdate()->first();abort_unless($bill&&(int)$bill->journal_entry_id===(int)$identity['bill_journal_id'],409);
  $cost=$db->table('landed_costs')->where('org_id',$mapping->finance_organization_id)->where('id',$identity['landed_cost_id'])->lockForUpdate()->first();abort_unless($cost&&(int)$cost->bill_id===(int)$bill->id,409);
  $op=$db->table('finance_landed_cost_operations')->where('organization_id',$mapping->finance_organization_id)->where('organization_mapping_uuid',$mapping->mapping_uuid)->where('landed_cost_id',$cost->id)->where('operation_uuid',$identity['operation_uuid'])->lockForUpdate()->first();abort_unless($op&&(int)$op->actor_id===$actor&&(int)$op->bill_id===(int)$bill->id&&(int)$op->bill_journal_id===(int)$bill->journal_entry_id&&$op->state===($proof['state']??null),409);
  abort_unless(hash_equals((string)$op->payload_hash,hash('sha256',$op->payload))&&hash_equals((string)$op->payload_hash,(string)($proof['payload_hash']??'')),409);$payload=json_decode($op->payload,true,512,JSON_THROW_ON_ERROR);
  abort_unless(SolaStockJournalContract::payloadHash($payload)===SolaStockJournalContract::payloadHash($proof['canonical_payload']??[]),403);
  abort_unless(substr((string)$cost->date,0,10)===($payload['date']??null)&&Decimal::cmp((string)$cost->exchange_rate,(string)$payload['exchange_rate'],12)===0&&Decimal::cmp((string)$cost->total_additional_cost,(string)$payload['amount'],8)===0&&empty($cost->deleted_at),409);
  foreach(['operation_uuid'=>$identity['operation_uuid'],'landed_cost_id'=>$cost->id,'source_bill_id'=>$bill->id,'bill_journal_id'=>$bill->journal_entry_id,'organization_mapping_uuid'=>$mapping->mapping_uuid]as$key=>$value)abort_unless((string)($payload[$key]??'')===(string)$value,409);
  abort_unless(($payload['schema_version']??null)==='purchasing.landed_cost.v1'&&($payload['base_currency_code']??null)===$mapping->base_currency_code&&Decimal::gt((string)($payload['exchange_rate']??'0'),'0')&&Decimal::gt((string)($payload['amount_base']??'0'),'0'),409);
  $nativeJournal=$db->table('journal_entries')->where('organization_id',$mapping->finance_organization_id)->where('id',$bill->journal_entry_id)->where('source_type','App\\Models\\Bill')->where('source_id',$bill->id)->lockForUpdate()->first();self::activeJournal($nativeJournal);
  $positions=[];$sourceRows=$payload['sources']??[];abort_unless(is_array($sourceRows)&&count($sourceRows)>0,409);$sorted=$sourceRows;usort($sorted,fn($a,$b)=>strcmp((string)$a['position_uuid'],(string)$b['position_uuid']));
  foreach($sorted as$source){$position=$db->table('finance_purchase_positions')->where('organization_id',$mapping->finance_organization_id)->where('organization_mapping_uuid',$mapping->mapping_uuid)->where('position_uuid',$source['position_uuid'])->where('bill_id',$bill->id)->where('bill_journal_id',$bill->journal_entry_id)->where('bill_line_id',$source['bill_line_id'])->lockForUpdate()->first();abort_unless($position&&!in_array($position->state,['reversal_pending','reversed'],true),409);$positionSnapshot=json_decode($position->snapshot,true);abort_unless((int)($positionSnapshot['item_external_id']??0)===(int)$source['item_external_id']&&(int)($positionSnapshot['unit_external_id']??0)===(int)$source['unit_external_id'],403);$positions[$source['position_uuid']]=$position;}
  $locked=IntegrationOrganizationMapping::query()->whereKey($mapping->id)->lockForUpdate()->firstOrFail();abort_unless($locked->status==='verified'&&$locked->activation_state==='active'&&(int)$locked->solastock_organization_id===$org&&(int)$locked->finance_organization_id===(int)$mapping->finance_organization_id&&$locked->mapping_uuid===$mapping->mapping_uuid&&(int)$locked->central_client_id===(int)$mapping->central_client_id&&(int)$locked->central_organization_id===$org&&$locked->tenant_database_identity===$db->getDatabaseName(),409);
  $sources=[];$total='0';$seen=[];$quantityByLine=[];usort($sourceRows,fn($a,$b)=>[(int)$a['receipt_id'],(int)$a['receipt_line_id']]<=>[(int)$b['receipt_id'],(int)$b['receipt_line_id']]);
  foreach($sourceRows as$source){
   $key=$source['position_uuid'].'|'.$source['receipt_line_id'];abort_unless(!isset($seen[$key]),409);$seen[$key]=true;
   $settlement=$db->table('finance_purchase_settlements')->where('organization_id',$mapping->finance_organization_id)->where('organization_mapping_uuid',$mapping->mapping_uuid)->where('position_uuid',$source['position_uuid'])->where('receipt_id',$source['receipt_id'])->where('receipt_line_id',$source['receipt_line_id'])->where('receipt_mapping_uuid',$source['receipt_mapping_uuid'])->where('receipt_journal_key',$source['receipt_journal_key'])->where('state','settled')->lockForUpdate()->first();abort_unless($settlement&&Decimal::cmp((string)$settlement->quantity,(string)$source['quantity'],8)===0,409);
   IntegrationDocumentLifecycleMapping::query()->where('organization_mapping_uuid',$mapping->mapping_uuid)->where('mapping_uuid',$source['receipt_mapping_uuid'])->where('source_document_type','goods_receipt')->where('source_document_id',(string)$source['receipt_id'])->firstOrFail();
   $receipt=GoodsReceipt::withoutGlobalScope('warehouse_access')->where('organization_id',$org)->whereKey($source['receipt_id'])->lockForUpdate()->firstOrFail();abort_unless($receipt->status==='posted'&&!$receipt->reversal_id,409);$line=$receipt->lines()->whereKey($source['receipt_line_id'])->lockForUpdate()->firstOrFail();
   foreach(['item'=>[$line->item_id,$source['item_external_id']],'unit'=>[$line->entered_unit_id,$source['unit_external_id']]]as$type=>$pair)abort_unless(IntegrationMasterDataMapping::query()->where('organization_mapping_uuid',$mapping->mapping_uuid)->where('central_client_id',$mapping->central_client_id)->where('central_organization_id',$mapping->central_organization_id)->where('finance_organization_id',$mapping->finance_organization_id)->where('solastock_organization_id',$org)->where('entity_type',$type)->where('solastock_record_id',(string)$pair[0])->where('solabooks_record_id',(string)$pair[1])->where('status','verified')->whereNull('conflict_code')->whereNull('error_state')->where('solastock_archived',false)->where('solabooks_archived',false)->exists(),403);
   $journal=IntegrationOutboxEvent::query()->where('organization_id',$org)->where('event_type','grn.posted')->where('aggregate_id',$receipt->id)->where('idempotency_key',$source['receipt_journal_key'])->firstOrFail();$imported=$db->table('journal_entries')->where('organization_id',$mapping->finance_organization_id)->where('source_key','external-api:'.hash('sha256',$source['receipt_journal_key']))->lockForUpdate()->first();self::activeJournal($imported);
   $factor=(string)($line->unit_conversion_factor?:'1');$quantity=Decimal::mul((string)$source['quantity'],$factor,8);abort_unless(Decimal::gt($quantity,'0')&&!Decimal::gt($quantity,(string)$line->accepted_qty)&&!Decimal::lt((string)$source['delta_base'],'0'),409);
   $quantityByLine[$line->id]=Decimal::add($quantityByLine[$line->id]??'0',$quantity,8);abort_unless(!Decimal::gt($quantityByLine[$line->id],(string)$line->accepted_qty),409);
   $total=Decimal::add($total,(string)$source['delta_base'],8);$sources[]=$source+['item_id'=>(int)$line->item_id,'warehouse_id'=>(int)$receipt->warehouse_id,'quantity_base'=>$quantity,'receipt_unit_cost_base'=>(string)$line->unit_cost,'receipt_exchange_rate'=>(string)data_get($journal->payload,'currency.exchange_rate'),'organization_mapping_uuid'=>$mapping->mapping_uuid];
  }
  abort_unless(Decimal::cmp($total,(string)$payload['amount_base'],8)===0,409);
  if($action==='prepare')abort_unless(!$op->journal_entry_id&&in_array($op->state,['prepared','quoted'],true),409);
  if($action==='apply'){abort_unless((int)$op->journal_entry_id>0&&(int)$cost->journal_entry_id===(int)$op->journal_entry_id&&(int)($proof['landed_cost_journal_id']??0)===(int)$op->journal_entry_id&&hash_equals((string)$op->plan_fingerprint,(string)($proof['plan_fingerprint']??'')),409);$costJournal=$db->table('journal_entries')->where('organization_id',$mapping->finance_organization_id)->where('id',$op->journal_entry_id)->where('source','AP-LANDED-COST')->where('source_type','App\\Models\\LandedCost')->where('source_id',$cost->id)->lockForUpdate()->first();self::activeJournal($costJournal);}
  // Reverse/release cannot be inferred from a forward operation. Canonical lifecycle intent is mandatory.
  if(in_array($action,['reverse','release'],true))abort(409,'The native landed-cost lifecycle intent is not available.');
  $settings=$db->table('organizations')->where('id',$mapping->finance_organization_id)->first();$scale=(int)($settings->money_scale??2);abort_unless($scale>=0&&$scale<=6,409);
  return new self($payload,$sources,$proof,$org,(int)$mapping->finance_organization_id,$scale);
 }
 private static function activeJournal(?object $journal):void{abort_unless($journal&&$journal->status==='posted'&&!empty($journal->posted_at)&&empty($journal->voided_at)&&empty($journal->deleted_at),409);}
 public function operationUuid():string{return$this->facts['operation_uuid'];} public function organizationId():int{return$this->stockOrg;} public function financeOrganizationId():int{return$this->financeOrg;} public function mappingUuid():string{return$this->facts['organization_mapping_uuid'];}
 public function landedCostId():int{return(int)$this->facts['landed_cost_id'];} public function sourceBillId():int{return(int)$this->facts['source_bill_id'];} public function billJournalId():int{return(int)$this->facts['bill_journal_id'];} public function actorId():int{return(int)$this->proof['actor_id'];} public function action():string{return$this->proof['operation'];}
 public function payloadHash():string{return$this->proof['payload_hash'];} public function fingerprint():string{return hash('sha256','landed-cost|'.$this->mappingUuid().'|'.$this->operationUuid().'|'.$this->payloadHash());}
 public function currencyCode():string{return$this->facts['currency_code'];} public function baseCurrencyCode():string{return$this->facts['base_currency_code'];} public function exchangeRate():string{return(string)$this->facts['exchange_rate'];} public function moneyScale():int{return$this->scale;} public function sourceAllocations():array{return$this->sources;}
 public function financeJournalId():?int{return!empty($this->proof['landed_cost_journal_id'])?(int)$this->proof['landed_cost_journal_id']:null;} public function financeJournalKey():string{return'landed-cost:'.$this->operationUuid();} public function reversalJournalId():?int{return!empty($this->proof['reversal_journal_id'])?(int)$this->proof['reversal_journal_id']:null;} public function reversalJournalKey():string{return'landed-cost-reversal:'.$this->operationUuid();}
 public function planFingerprint():?string{return$this->proof['plan_fingerprint']??null;} public function planRevision():int{return 1;} public function holdGroup():array{return['purpose'=>'landed_cost','operation_uuid'=>$this->operationUuid()];}
 public function holdUuid(int$item,int$warehouse,string$direction='apply'):string{return Uuid::uuid5(Uuid::NAMESPACE_URL,'landed-cost|'.$this->mappingUuid().'|'.$this->operationUuid().'|'.$item.'|'.$warehouse.'|'.$direction)->toString();}
}
