<?php
namespace Tests\Feature\Sales;
use App\Models\Tenant\{FulfillmentDemandCommand,FulfillmentRequest,Reservation,SalesOrder,StockLedger};
use App\Models\User;
use App\Services\Documents\SalesOrderService;
use App\Services\Integration\SolaBooksOutboxDeliveryService;
use App\Services\Sales\{CreditDemandService,FulfillmentRequestService};
use Illuminate\Support\Facades\{Auth,DB};
use Illuminate\Support\Str;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Tests\Support\SalesHandoffFixture;
use Tests\TestCase;
use Tests\Traits\TenantAware;
final class CreditDemandHandoffTest extends TestCase {
 use TenantAware,SalesHandoffFixture;
 private function setupDemand():array {
  $this->useTenantA();$schema=DB::connection('tenant')->getSchemaBuilder();
  if(!$schema->hasTable('credit_notes'))$schema->create('credit_notes',function($t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('invoice_id')->nullable();});
  if(!$schema->hasTable('finance_sales_credit_demands'))$schema->create('finance_sales_credit_demands',function($t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('invoice_id');$t->unsignedBigInteger('invoice_journal_id');$t->unsignedBigInteger('credit_note_id');$t->uuid('operation_uuid');$t->uuid('request_uuid');$t->char('request_revision',64);$t->char('credit_revision',64);$t->string('state');$t->unsignedBigInteger('credit_journal_id')->nullable();$t->json('payload');});
  if(!$schema->hasColumn('journal_entries','source'))$schema->table('journal_entries',fn($t)=>$t->string('source')->nullable());
  $this->initializeSalesFixture(true);$data=$this->data();$data['source_status']='posted';$data['posted_invoice_journal_id']=70;
  DB::connection('tenant')->table('journal_entries')->insert(['id'=>70,'organization_id'=>14,'source_type'=>'App\\Models\\Invoice','source_id'=>800,'status'=>'posted']);$this->authority($data);
  $actor=new User;$actor->id=323;Auth::setUser($actor);request()->setUserResolver(fn()=>$actor);$this->mock(\App\Services\Access\CentralAppAccess::class)->shouldReceive('decision')->andReturn(['allowed'=>true,'owner'=>true,'roles'=>[]]);$this->app->forgetInstance(\App\Services\Access\InventoryPermissionService::class);$r=app(FulfillmentRequestService::class)->upsert($data,323);app(FulfillmentRequestService::class)->approve(FulfillmentRequest::sole(),$this->warehouse->id);
  $order=SalesOrder::sole();app(SalesOrderService::class)->reserve($order);
  DB::connection('tenant')->table('credit_notes')->insert(['id'=>90,'organization_id'=>14,'invoice_id'=>800]);
  $command=['source_invoice_id'=>800,'request_uuid'=>$data['request_uuid'],'source_revision'=>$data['source_revision'],'credit_note_id'=>90,'operation_uuid'=>(string)Str::uuid(),'credit_revision'=>str_repeat('c',64),'purpose'=>'prepare','lines'=>[['source_invoice_line_id'=>'801','credit_note_line_id'=>91,'unfulfilled_quantity'=>'1']]];
  DB::connection('tenant')->table('finance_sales_credit_demands')->insert(['organization_id'=>14,'invoice_id'=>800,'invoice_journal_id'=>70,'credit_note_id'=>90,'operation_uuid'=>$command['operation_uuid'],'request_uuid'=>$command['request_uuid'],'request_revision'=>$command['source_revision'],'credit_revision'=>$command['credit_revision'],'state'=>'preparing','payload'=>json_encode(['lines'=>$command['lines']])]);return$command;
 }
 private function proof(array$c,array$extra=[]):void {$response=array_replace(['command'=>'reduce-demand','purpose'=>$c['purpose'],'request_uuid'=>$c['request_uuid'],'request_revision'=>$c['source_revision'],'operation_uuid'=>$c['operation_uuid'],'credit_note_id'=>90,'credit_revision'=>$c['credit_revision'],'invoice_journal_id'=>70,'lines'=>$c['lines']],$extra);$this->mock(SolaBooksOutboxDeliveryService::class)->shouldReceive('authorizeSales')->andReturn($response);}
 public function test_prepared_credit_fences_dispatch_and_exact_posted_credit_commits_once_without_physical_movement():void {
  $c=$this->setupDemand();$order=SalesOrder::sole();$shipmentService=app(\App\Services\Documents\ShipmentService::class);$shipment=$shipmentService->post($shipmentService->createDraft(['shipment_number'=>'QA-CREDIT-PARTIAL','sales_order_id'=>$order->id,'warehouse_id'=>$order->warehouse_id],[['sales_order_line_id'=>$order->lines->sole()->id,'item_id'=>$order->lines->sole()->item_id,'quantity'=>'1']]));config(['inventory.demo_tenant.enabled'=>false]);$this->mock(\App\Services\Access\CentralAppAccess::class)->shouldReceive('decision')->andReturn(['allowed'=>false]);$actor=new User;$actor->id=901;Auth::setUser($actor);request()->setUserResolver(fn()=>$actor);$this->assertFalse(app(\App\Services\Access\InventoryPermissionService::class)->can($actor,'inventory.manage_shipments'));$this->proof($c);$service=app(CreditDemandService::class);$before=StockLedger::count();$prepared=$service->dispatch($c,901);$this->assertSame('prepared',$prepared['state']);$this->assertSame($prepared,$service->dispatch($c,901));
  try{app(FulfillmentRequestService::class)->guardOrderDemand((int)FulfillmentRequest::sole()->sales_order_id);$this->fail('Prepared credit allowed dispatch');}catch(HttpException$e){$this->assertSame(409,$e->getStatusCode());}
  DB::connection('tenant')->table('journal_entries')->insert(['id'=>80,'organization_id'=>14,'source'=>'NOTE','source_type'=>'App\\Models\\CreditNote','source_id'=>90,'status'=>'posted']);DB::connection('tenant')->table('finance_sales_credit_demands')->update(['state'=>'commit_pending','credit_journal_id'=>80]);
  $c['purpose']='commit';$c['hold_fingerprint']=$prepared['hold_fingerprint'];$this->proof($c,['credit_journal_id'=>80,'hold_fingerprint'=>$prepared['hold_fingerprint']]);$committed=$service->dispatch($c,901);$this->assertSame('committed',$committed['state']);$this->assertSame($committed,$service->dispatch($c,901));$this->assertSame('1.0000',FulfillmentRequest::sole()->lines->sole()->cancelled_qty);$this->assertSame('4.0000',FulfillmentRequest::sole()->lines->sole()->requested_qty);$this->assertSame('2.0000',(string)Reservation::withoutGlobalScope('warehouse_access')->where('status','active')->sum('qty'));$this->assertSame([$shipment->id],$committed['fulfillment_request']['shipment_ids']);$this->assertSame('1.0000',$committed['fulfillment_request']['lines'][0]['fulfilled_quantity']);$this->assertSame('2.0000000000',$committed['fulfillment_request']['lines'][0]['remaining_qty']);$this->assertSame($before,StockLedger::count());$this->assertSame(1,FulfillmentDemandCommand::count());
 }
 public function test_abandoned_no_journal_credit_releases_only_the_hold_and_cannot_later_commit():void {
  $c=$this->setupDemand();$this->proof($c);$service=app(CreditDemandService::class);$prepared=$service->dispatch($c,323);DB::connection('tenant')->table('finance_sales_credit_demands')->update(['state'=>'abandon_pending']);$c['purpose']='abandon';$c['hold_fingerprint']=$prepared['hold_fingerprint'];$this->proof($c,['hold_fingerprint'=>$prepared['hold_fingerprint']]);$this->assertSame('abandoned',$service->dispatch($c,323)['state']);$this->assertSame('0.0000',FulfillmentRequest::sole()->lines->sole()->cancelled_qty);$this->assertSame('4.0000',(string)Reservation::withoutGlobalScope('warehouse_access')->where('status','active')->sum('qty'));
  $c['purpose']='commit';$this->proof($c,['hold_fingerprint'=>$prepared['hold_fingerprint']]);try{$service->dispatch($c,323);$this->fail('Abandoned credit committed');}catch(HttpException$e){$this->assertSame(409,$e->getStatusCode());}
 }
 public function test_price_only_zero_quantity_credit_does_not_hold_dispatch_or_release_reservations():void {
  $c=$this->setupDemand();$c['lines'][0]['unfulfilled_quantity']='0';DB::connection('tenant')->table('finance_sales_credit_demands')->update(['payload'=>json_encode(['lines'=>$c['lines']])]);$this->proof($c);$service=app(CreditDemandService::class);$prepared=$service->dispatch($c,323);app(FulfillmentRequestService::class)->guardOrderDemand((int)FulfillmentRequest::sole()->sales_order_id);$this->assertSame('4.0000',(string)Reservation::withoutGlobalScope('warehouse_access')->where('status','active')->sum('qty'));
  DB::connection('tenant')->table('journal_entries')->insert(['id'=>80,'organization_id'=>14,'source'=>'NOTE','source_type'=>'App\\Models\\CreditNote','source_id'=>90,'status'=>'posted']);DB::connection('tenant')->table('finance_sales_credit_demands')->update(['state'=>'commit_pending','credit_journal_id'=>80]);$c['purpose']='commit';$c['hold_fingerprint']=$prepared['hold_fingerprint'];$this->proof($c,['credit_journal_id'=>80,'hold_fingerprint'=>$prepared['hold_fingerprint']]);$before=StockLedger::count();$service->dispatch($c,323);$this->assertSame('0.0000',FulfillmentRequest::sole()->lines->sole()->cancelled_qty);$this->assertSame('4.0000',(string)Reservation::withoutGlobalScope('warehouse_access')->where('status','active')->sum('qty'));$this->assertSame($before,StockLedger::count());
 }
 public function test_forged_credit_line_or_financial_journal_proof_cannot_publish_demand_hold():void {
  $c=$this->setupDemand();$this->proof($c,['invoice_journal_id'=>999]);try{app(CreditDemandService::class)->dispatch($c,323);$this->fail('Forged Invoice journal accepted');}catch(HttpException$e){$this->assertSame(409,$e->getStatusCode());}$this->assertSame(0,FulfillmentDemandCommand::count());
  $other=$c;$other['lines'][0]['source_invoice_line_id']='999';$this->proof($c);try{app(CreditDemandService::class)->dispatch($other,323);$this->fail('Forged credit source line accepted');}catch(HttpException$e){$this->assertSame(403,$e->getStatusCode());}$this->assertSame(0,FulfillmentDemandCommand::count());
  $context=app(\App\Tenancy\OrganizationContext::class);$old=$context->idOrFail();$context->set(999999);$this->proof($c);try{app(CreditDemandService::class)->dispatch($c,323);$this->fail('Foreign organization consumed authenticated credit proof');}catch(\Illuminate\Database\Eloquent\ModelNotFoundException$e){$this->assertTrue(true);}catch(HttpException$e){$this->assertContains($e->getStatusCode(),[403,404,409]);}finally{$context->set($old);}$this->assertSame(0,FulfillmentDemandCommand::count());
 }
 public function test_safe_abandoned_correction_creates_a_new_command_without_resurrecting_original_history():void {
  $c=$this->setupDemand();$this->proof($c);$service=app(CreditDemandService::class);$old=$service->dispatch($c,323);$originalHash=FulfillmentDemandCommand::sole()->payload_hash;DB::connection('tenant')->table('finance_sales_credit_demands')->update(['state'=>'abandon_pending']);$c['purpose']='abandon';$c['hold_fingerprint']=$old['hold_fingerprint'];$this->proof($c,['hold_fingerprint'=>$old['hold_fingerprint']]);$service->dispatch($c,323);
  $new=$c;unset($new['hold_fingerprint']);$new['purpose']='prepare';$new['operation_uuid']=(string)Str::uuid();$new['credit_revision']=str_repeat('d',64);$new['lines'][0]['unfulfilled_quantity']='2';DB::connection('tenant')->table('finance_sales_credit_demands')->update(['operation_uuid'=>$new['operation_uuid'],'credit_revision'=>$new['credit_revision'],'state'=>'preparing','payload'=>json_encode(['lines'=>$new['lines']])]);$this->proof($new);$result=$service->dispatch($new,323);$this->assertSame('prepared',$result['state']);$this->assertSame($result,$service->dispatch($new,323));$this->assertSame(2,FulfillmentDemandCommand::count());$prior=FulfillmentDemandCommand::where('operation_uuid',$c['operation_uuid'])->sole();$this->assertSame('abandoned',$prior->state);$this->assertSame($originalHash,$prior->payload_hash);
  $c['purpose']='prepare';unset($c['hold_fingerprint']);$this->proof($c);try{$service->dispatch($c,323);$this->fail('Old abandoned operation resurrected');}catch(HttpException$e){$this->assertSame(409,$e->getStatusCode());}$this->assertSame(2,FulfillmentDemandCommand::count());
 }
 private function setupReverse():array {
  $this->useTenantA();$db=DB::connection('tenant');$schema=$db->getSchemaBuilder();
  if(!$schema->hasTable('credit_notes'))$schema->create('credit_notes',function($t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('invoice_id')->nullable();});
  if(!$schema->hasTable('finance_sales_credit_demands'))$schema->create('finance_sales_credit_demands',function($t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('invoice_id');$t->unsignedBigInteger('invoice_journal_id');$t->unsignedBigInteger('credit_note_id');$t->uuid('operation_uuid');$t->uuid('request_uuid');$t->char('request_revision',64);$t->char('credit_revision',64);$t->string('state');$t->unsignedBigInteger('credit_journal_id')->nullable();$t->json('payload');});
  foreach(['status']as$column)if(!$schema->hasColumn('credit_notes',$column))$schema->table('credit_notes',fn($t)=>$t->string($column)->nullable());
  foreach(['reverse_operation_uuid','closure_permission','reversal_state','reversal_snapshot','reverse_actor_id']as$column)if(!$schema->hasColumn('finance_sales_credit_demands',$column))$schema->table('finance_sales_credit_demands',function($t)use($column){if($column==='reverse_actor_id')$t->unsignedBigInteger($column)->nullable();elseif($column==='reversal_snapshot')$t->json($column)->nullable();else$t->string($column)->nullable();});
  if(!$schema->hasColumn('journal_entries','voided_by'))$schema->table('journal_entries',fn($t)=>$t->unsignedBigInteger('voided_by')->nullable());
  if(!$schema->hasTable('action_logs'))$schema->create('action_logs',function($t){$t->id();$t->string('controller');$t->string('method');$t->unsignedBigInteger('user_id');$t->json('data');});
  if(!$schema->hasTable('tax_lines'))$schema->create('tax_lines',function($t){$t->id();$t->unsignedBigInteger('org_id');$t->string('taxable_type');$t->unsignedBigInteger('taxable_id');$t->unsignedBigInteger('tax_id');$t->unsignedBigInteger('tax_account_id');$t->date('tax_date');$t->decimal('base_amount',18,4);$t->decimal('tax_amount',18,4);});
  if(!$schema->hasTable('finance_sales_credit_allocations'))$schema->create('finance_sales_credit_allocations',function($t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('credit_note_id');$t->unsignedBigInteger('journal_entry_id');$t->string('state');});
  $c=$this->setupDemand();$db=DB::connection('tenant');$this->proof($c);$service=app(CreditDemandService::class);$prepared=$service->dispatch($c,323);
  $db->table('journal_entries')->insert(['id'=>80,'organization_id'=>14,'source'=>'NOTE','source_type'=>'App\\Models\\CreditNote','source_id'=>90,'status'=>'posted']);$db->table('credit_notes')->where('id',90)->update(['status'=>'posted']);$db->table('finance_sales_credit_demands')->update(['state'=>'commit_pending','credit_journal_id'=>80]);$c['purpose']='commit';$c['hold_fingerprint']=$prepared['hold_fingerprint'];$this->proof($c,['credit_journal_id'=>80,'hold_fingerprint'=>$prepared['hold_fingerprint']]);$service->dispatch($c,323);
  $c['purpose']='reverse_prepare';unset($c['hold_fingerprint']);$c['reversal_operation_uuid']=(string)Str::uuid();$c['closure_permission']='void';$c['original_credit_journal_id']=80;$db->table('finance_sales_credit_demands')->update(['reverse_operation_uuid'=>$c['reversal_operation_uuid'],'reverse_actor_id'=>777,'closure_permission'=>'void','reversal_state'=>'reverse_preparing']);$this->reverseProof($c);return$c;
 }
 private function reverseProof(array$c,array$extra=[]):void {$this->proof($c,array_replace(['reversal_operation_uuid'=>$c['reversal_operation_uuid'],'closure_permission'=>'void','original_credit_journal_id'=>80,'reverse_actor_id'=>777],$extra));}
 private function voidFacts(array$c):array {
  $db=DB::connection('tenant');$audit=$db->table('action_logs')->insertGetId(['controller'=>'ReversalEngine','method'=>'voidCreditNote','user_id'=>777,'data'=>json_encode(['document_type'=>'App\\Models\\CreditNote','document_id'=>90])]);$db->table('credit_notes')->where('id',90)->update(['status'=>'void']);$db->table('journal_entries')->where('id',80)->update(['status'=>'voided','voided_at'=>now(),'voided_by'=>777]);$snapshot=['void_audit_id'=>$audit,'original_credit_journal_id'=>80,'credit_note_id'=>90,'invoice_journal_id'=>70,'void_actor_id'=>777,'credit_status'=>'void','journal_status'=>'voided','allocation_ids'=>[],'tax_line_ids'=>[],'tax_offset_ids'=>[]];$tax=['org_id'=>14,'taxable_type'=>'App\\Models\\CreditNote','taxable_id'=>90,'tax_id'=>5,'tax_account_id'=>21,'tax_date'=>'2026-10-07'];$snapshot['tax_line_ids']=[$db->table('tax_lines')->insertGetId($tax+['base_amount'=>'1','tax_amount'=>'0.16'])];$snapshot['tax_offset_ids']=[$db->table('tax_lines')->insertGetId($tax+['base_amount'=>'-1','tax_amount'=>'-0.16'])];$snapshot['allocation_ids']=[$db->table('finance_sales_credit_allocations')->insertGetId(['organization_id'=>14,'credit_note_id'=>90,'journal_entry_id'=>80,'state'=>'reversed'])];$db->table('finance_sales_credit_demands')->update(['reversal_state'=>'reverse_commit_pending','reversal_snapshot'=>json_encode($snapshot)]);return$snapshot;
 }
 public function test_native_audited_credit_void_restores_only_own_demand_once_without_stock_or_reservation():void {
  $c=$this->setupReverse();$service=app(CreditDemandService::class);$before=StockLedger::count();$reserved=Reservation::sum('qty');$hold=$service->dispatch($c,901);$this->assertSame('reverse_prepared',$hold['state']);try{app(FulfillmentRequestService::class)->guardOrderDemand((int)FulfillmentRequest::sole()->sales_order_id);$this->fail('Reverse hold allowed dispatch');}catch(HttpException$e){$this->assertSame(409,$e->getStatusCode());}
  $snapshot=$this->voidFacts($c);$c['purpose']='reverse_commit';$c['hold_fingerprint']=$hold['hold_fingerprint'];$this->reverseProof($c,['hold_fingerprint'=>$hold['hold_fingerprint'],'reversal_snapshot'=>$snapshot]);$restored=$service->dispatch($c,901);$this->assertSame('reversed',$restored['state']);$this->assertSame($restored,$service->dispatch($c,901));$this->assertSame('0.0000',FulfillmentRequest::sole()->lines->sole()->cancelled_qty);$this->assertSame('4.0000',FulfillmentRequest::sole()->lines->sole()->requested_qty);$this->assertSame($reserved,Reservation::sum('qty'));$this->assertSame($before,StockLedger::count());
 }
 public function test_credit_reverse_cannot_restore_demand_without_exact_native_void_audit():void {
  $c=$this->setupReverse();$service=app(CreditDemandService::class);$hold=$service->dispatch($c,901);$snapshot=$this->voidFacts($c);DB::connection('tenant')->table('action_logs')->where('id',$snapshot['void_audit_id'])->update(['data'=>json_encode(['document_type'=>'App\\Models\\CreditNote','document_id'=>999])]);$c['purpose']='reverse_commit';$c['hold_fingerprint']=$hold['hold_fingerprint'];$this->reverseProof($c,['hold_fingerprint'=>$hold['hold_fingerprint'],'reversal_snapshot'=>$snapshot]);try{$service->dispatch($c,901);$this->fail('Foreign audit restored demand');}catch(HttpException$e){$this->assertSame(409,$e->getStatusCode());}$this->assertSame('1.0000',FulfillmentRequest::sole()->lines->sole()->cancelled_qty);$this->assertSame('reverse_prepared',FulfillmentDemandCommand::sole()->state);
 }
 public function test_no_void_reverse_abandon_releases_hold_preserving_committed_credit_quantity():void {
  $c=$this->setupReverse();$service=app(CreditDemandService::class);$hold=$service->dispatch($c,901);DB::connection('tenant')->table('finance_sales_credit_demands')->update(['reversal_state'=>'reverse_abandon_pending']);$c['purpose']='reverse_abandon';$c['hold_fingerprint']=$hold['hold_fingerprint'];$this->reverseProof($c,['hold_fingerprint'=>$hold['hold_fingerprint']]);$abandoned=$service->dispatch($c,901);$this->assertSame('committed',$abandoned['state']);$this->assertSame($abandoned,$service->dispatch($c,901));$this->assertSame('1.0000',FulfillmentRequest::sole()->lines->sole()->cancelled_qty);app(FulfillmentRequestService::class)->guardOrderDemand((int)FulfillmentRequest::sole()->sales_order_id);
 }

 public function test_native_credit_void_requires_exact_nonzero_vat_offset_and_allocation_ownership():void {
  $c=$this->setupReverse();$service=app(CreditDemandService::class);$hold=$service->dispatch($c,901);$snapshot=$this->voidFacts($c);$c['purpose']='reverse_commit';$c['hold_fingerprint']=$hold['hold_fingerprint'];$this->reverseProof($c,['hold_fingerprint'=>$hold['hold_fingerprint'],'reversal_snapshot'=>$snapshot]);$before=StockLedger::count();DB::connection('tenant')->table('tax_lines')->where('id',$snapshot['tax_offset_ids'][0])->update(['tax_amount'=>'-0.15']);try{$service->dispatch($c,901);$this->fail('Unbalanced native VAT offset restored demand');}catch(HttpException$e){$this->assertSame(409,$e->getStatusCode());}$this->assertSame('1.0000',FulfillmentRequest::sole()->lines->sole()->cancelled_qty);DB::connection('tenant')->table('tax_lines')->where('id',$snapshot['tax_offset_ids'][0])->update(['tax_amount'=>'-0.16']);DB::connection('tenant')->table('finance_sales_credit_allocations')->where('id',$snapshot['allocation_ids'][0])->update(['journal_entry_id'=>999]);try{$service->dispatch($c,901);$this->fail('Foreign financial allocation restored demand');}catch(HttpException$e){$this->assertSame(409,$e->getStatusCode());}$this->assertSame($before,StockLedger::count());$this->assertSame('reverse_prepared',FulfillmentDemandCommand::sole()->state);
 }

 public function test_credit_void_preserves_independently_cancelled_fulfillment_without_reopening_or_reserving():void {
  $c=$this->setupReverse();$r=FulfillmentRequest::sole();$cancel=$r->source_payload;$cancel['expected_revision']=$r->source_revision;$this->authority($cancel,['command'=>'cancel','request_uuid'=>$r->request_uuid,'command_source_revision'=>$r->source_revision,'expected_revision'=>$r->source_revision],'cancel');$this->mock(SolaBooksOutboxDeliveryService::class)->shouldReceive('authorizeSales')->with(323,800,'post',['command'=>'cancel','request_uuid'=>$r->request_uuid,'source_revision'=>$r->source_revision,'expected_revision'=>$r->source_revision])->andReturn(['command'=>'cancel','request_uuid'=>$r->request_uuid,'command_source_revision'=>$r->source_revision,'expected_revision'=>$r->source_revision]);$cancelled=app(FulfillmentRequestService::class)->cancel($cancel,323);$this->assertSame('cancelled',$cancelled['status']);$this->assertSame('cancelled',SalesOrder::sole()->status);$this->assertSame('0.0000',(string)Reservation::where('status','active')->sum('qty'));$before=StockLedger::count();$this->reverseProof($c);$service=app(CreditDemandService::class);$hold=$service->dispatch($c,901);$snapshot=$this->voidFacts($c);$c['purpose']='reverse_commit';$c['hold_fingerprint']=$hold['hold_fingerprint'];$this->reverseProof($c,['hold_fingerprint'=>$hold['hold_fingerprint'],'reversal_snapshot'=>$snapshot]);$result=$service->dispatch($c,901);$this->assertSame('reversed',$result['state']);$this->assertSame('cancelled',$result['fulfillment_request']['status']);$this->assertSame('cancelled',SalesOrder::sole()->status);$this->assertSame('0.0000',FulfillmentRequest::sole()->lines->sole()->cancelled_qty);$this->assertSame('0.0000',(string)Reservation::where('status','active')->sum('qty'));$this->assertSame($before,StockLedger::count());
 }

}
